= Configuring common Linux options

:experimental:

== Compress memory using zswap [[zswap]]

`zswap` is a kernel feature that compresses data in RAM that would otherwise need to be written to the swap partition. In effect, it increases the amount of data that can be stored in RAM, lowers swap partition usage, and increases overall system performance, especially when using a slow disk and little RAM.

. Enable it in `/etc/default/grub`:
+
----
zswap.enabled=1 zswap.shrinker_enabled=1
----

. On systems with very low memory, add the following options to increase memory compression:

** In `/etc/default/grub`:
+
----
zswap.compressor=zstd zswap.max_pool_percent=40
----

** In `/etc/modules-load.d/zstd.conf`, ensure that the kernel loads the Zstd compression module:
+
----
zstd
----

. Update `grub2` configuration as described in <<update-grub>>

. Reboot.

. Verify that `zswap` is active:

** Read the current state of `zswap` from the `/sys/module/zswap/parameters/enabled` file: N for off, Y for on.

** Run-time `zswap` statistics are recorded in the `/sys/kernel/debug/zswap` file.


== Enable system logging in a console [[console-log]]

You can configure your system log service to print log entries in a system console: for example, TTY10.

. Add the following lines to the `/etc/systemd/journald.conf` configuration file:
+
[subs=+quotes]
----
ForwardToConsole=yes
TTYPath=/dev/tty__N__
----
+
Replace `__N__` with the number of the console of your choosing. Note that Fedora assigns graphical user interfaces to `tty1` and subsequent consoles, while more traditional distributions like Debian start from `tty7`.

. Restart the `journald` service:
+
[source,bash]
----
sudo systemctl restart systemd-journald
----


== Select a disk scheduler [[blk-mq]]

By default, Linux selects between the `none` and `mq-deadline` disk schedulers. The BFQ disk scheduler provides better interactive performance even on SSD and NVMe disks. You can enable BFQ on all storage devices:

. To load the BFQ module, create the `/etc/modules-load.d/bfq.conf` file with the following content:
+
----
bfq
----

. Load the `bfq` module at runtime:
+
[source,bash]
----
sudo modprobe bfq
----

. Create the `/etc/udev/rules.d/60-scheduler.rules` file.
+
In it, set BFQ for your preferred set of devices:

** Set BFQ for all rotational devices:
+
----
ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
----

** Set BFQ for all storage devices, including SATA and NVMe:
+
----
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="bfq"
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="nvme*", ATTR{queue/scheduler}="bfq"
----

** Set BFQ for all devices, including virtual devices (not recommended):
+
----
ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/scheduler}!="bfq", ATTR{queue/scheduler}="bfq"
----

. Apply the new configuration:
+
[source,bash]
----
sudo udevadm control --reload-rules
sudo udevadm trigger --type=devices --action=change
----

. Check that the BFQ scheduler is active:
+
[source,bash]
----
grep . /sys/block/*/queue/scheduler
----

For other configuration options, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance[Setting the disk scheduler] in the RHEL 9 documentation.


== Enable an early OOM killer [[early-oom]]

The Linux "out-of-memory killer" (OOM Killer) is supposed to terminate the process that uses the most memory when the system is running out of RAM. However, it hardly ever actually executes: it is overly optimistic that the system can eventually handle the problem on its own. This leads to situations when the memory is hopelessly full while the system stays unresponsive for hours until the user presses the power button.

Therefore, an alternative, user-space implementation has been created, `earlyoom`, which is much more strict and predictable.

The `earlyoom` service runs in the background and checks for memory conditions. By default, it kills a process when both the RAM and the swap partition are at least 90% full. These values are configurable.

For details on installation and usage, see the GitHub page: https://github.com/rfjakob/earlyoom[rfjakob/earlyoom]. The context was also discussed on Reddit: https://www.reddit.com/r/linux/comments/7e0pgm/earlyoom_early_oom_daemon/[earlyoom - Early OOM daemon].

The `earlyoom` service is packaged both for Fedora and Debian.

== Tune memory for interactive use [[memory-tuning]]

https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[Certain people] argue that the way Linux handles interactive desktop usage leaves much to be desired. They also suggest ways to improve that.

In the `/etc/sysctl.conf` file, set:

----
vm.swappiness=10
vm.vfs_cache_pressure=50
----

Or, if you want to be more conservative, set:

----
vm.swappiness=20
vm.vfs_cache_pressure=80
----

In comparison, the default values are:

----
vm.swappiness=60
vm.vfs_cache_pressure=100
----

However, note that there is little "scientific" proof that modifying these actually helps. Experiment if you need to be sure. Rodd-O https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[devises a way to test the impact] in their article mentioned earlier.

Afterwards, update the initial ramdisk; see <<rebuild-initramfs>>.

== Set up the Magic SysRq Keys [[magic-sysrq]]

"Magic SysRq Keys" are keyboard shortcuts that are registered at the kernel level and allow you to control the basic functions of system even if it has otherwise completely frozen.

A common use case is to shut down the frozen system safely:

. kbd:[Alt+SysRq+s] to write (sync) all disk buffers.
. kbd:[Alt+SysRq+u] to remount all disks read-only.
. kbd:[Alt+SysRq+b] to reboot the system immediately.

Many more shortcuts are listed in the https://en.wikipedia.org/wiki/Magic_SysRq_key#Commands[Magic SysRq key] article on Wikipedia.

To set up Magic SysRq:

. Open the `/etc/sysctl.conf` file as root and add:
+
----
kernel.sysrq = 1
----

. Update the initial ramdisk. See <<rebuild-initramfs>>.

== Disable watchdog

`watchdog` is a kernel service, which allows to debug system lock-ups. However, to be honest, it's really not that useful for you as a desktop user. On the other hand, it periodically creates interrupts, which wake the CPU up from low-power sleep. Therefore, if power consumption is a concern, you can safely turn `watchdog` off.

There are two main ways to configure `watchdog`: in a kernel parameter or using `sysctl`. They should have the same effect, so it's up to you which one to choose.

- To disable `watchdog` using a kernel parameter:

.. Edit the `/etc/default/grub` file and add the following to the kernel command line:
+
----
nmi_watchdog=0
----

.. Update `grub2` configuration as described in <<update-grub>>.

- To disable `watchdog` using `sysctl`, edit the `/etc/sysctl.conf` and add there:
+
----
kernel.nmi_watchdog=0
----

You can read the current state of `watchdog` from the `/proc/sys/kernel/nmi_watchdog` file: `0` for disabled, `1` for enabled`.

Finally, update the initial ramdisk. See <<rebuild-initramfs>>.

== Trim your SSD [[fstrim]]

If your computer uses a solid-state disk (SSD), you should https://en.wikipedia.org/wiki/Trim_(computing)["trim"] the file systems on it regularly. Your distributions might already do that for you: Ubuntu runs `fstrim` weekly.

On Fedora and Debian, you need to manually enable a service that trims disks periodically:

. If you're using Debian, copy the service file so that it can be actually used:
+
[source,bash]
----
sudo cp /usr/share/doc/util-linux/examples/fstrim.{service,timer} \
        -t /etc/systemd/system/
----

. Enable the weekly timer:
+
[source,bash]
----
sudo systemctl enable fstrim.timer
----

== Rebuild the initial ramdisk [[rebuild-initramfs]]

After changing `sysctl` settings, rebuilt the initial ramdisk in order for the updated settings to take effect early in the boot process.

- In Fedora:
+
[source,bash]
----
sudo dracut -f
----

- In Debian:
+
[source,bash]
----
sudo update-initramfs
----
+
Or:
+
[source,bash]
----
sudo dracut-update-initramfs
----

== Update GRUB configuration [[update-grub]]

After editing the `/etc/default/grub` file, the configuration has to be compiled for `grub2` to be able to use it:

- On Debian:
+
[source,bash]
----
sudo update-grub2
----

- On Fedora:

.. Locate the compiled configuration file:
+
[source,bash]
----
sudo find /boot -name grub.cfg
----

.. Copy the file name the previous command gave you and use it here:
+
[source,bash,subs=+quotes]
....
sudo grub2-mkconfig -o /boot/__path/to/__grub.cfg
....

== journald disk usage [[journald-disk-usage]]

The current disk usage of `journalctl` can be displayed using the following command:

[source,bash]
----
sudo journalctl --disk-usage
----

`journald` configuration is located in the `/etc/systemd/journald.conf` file. It's probably a good idea to explicitly limit how much data `journald` can store. In the configuration file, set something like:

----
SystemMaxUse=256M
RuntimeMaxUse=128M
----

== Synchronize time zones when dual-booting with Windows [[dual-boot-time-zones]]

Linux sets the hardware clock to the current time in UTC, while Windows sets it to the local time. This conflict results the clock being off a few hours when switching operating systems.

One solution is to persuade Linux to use local time instead. Surprisingly, this is extremely hard, as core system services expect UTC.

The other way is to configure Windows to use UTC. This is relatively easy. The Arch Linux Wiki describes the process in the https://wiki.archlinux.org/index.php/Time#UTC_in_Windows[UTC in Windows] section of the https://wiki.archlinux.org/index.php/Time[Time] article.

== Update the firmware

Some manufacturers (mostly Dell, Lenovo) provide firmware updates via the native Linux `fwupd` mechanism.

* To check for updates:
+
----
sudo fwupdmgr refresh
sudo fwupdmgr get-updates
----

* To apply them:
+
----
sudo fwupdmgr update
----

== Apply a Tuned profile for desktop responsiveness [[tuned-responsiveness]]

. Install and enable the `tuned` service.

. Create the `/etc/tuned/interactive/tuned.conf` file with the following content:
+
----
[main]
summary=My own Tuned profile for an interactive desktop system
include=desktop

[cpu]
governor=ondemand|powersave

[sysctl]
# The defaults on Fedora 30; these values are interdependent:
# kernel.sched_min_granularity_ns=2250000
# kernel.sched_latency_ns=18000000
# kernel.sched_wakeup_granularity_ns=3000000

# The defaults divided by 4 to reduce latency:
kernel.sched_min_granularity_ns=562500
kernel.sched_latency_ns=4500000
kernel.sched_wakeup_granularity_ns=750000

vm.swappiness=10
vm.vfs_cache_pressure=50

[disk]
# On all disks, use BFQ, which is an excellent scheduler for interactivity
elevator=bfq

[sysfs]
# Apply some tunings to sda, which should be the primary and also the fastest disk on your system (at least on desktops and laptops)

# Low latency in mq-deadline in case it's set instead of BFQ:
# /sys/block/sda/queue/iosched/fifo_batch=8
# /sys/block/sda/queue/iosched/read_expire=50

# Low latency in BFQ (optional because BFQ already works well on its own):
# Halve the idle wait time; should improve throughput on SSDs
/sys/block/sda/queue/iosched/slice_idle=4
# Halve the time to expire read requests
/sys/block/sda/queue/iosched/fifo_expire_sync=62
/sys/block/sda/queue/iosched/timeout_sync=62

# Power-saving features
[audio]
timeout=10
----

. Apply the profile:
+
----
sudo tuned-adm profile interactive
----


== Automatically uninstall unused Flatpak runtimes [[autoremove-flatpak-runtimes]]

As Flatpak applications update, they switch to newer versions of their runtimes. Flatpak still keeps the old runtimes installed even after no application depends on it anymore. The unused runtimes might then occupy a significant amount of disk space.

You can configure a systemd timer unit to automatically remove unused runtimes once a week.

. Save the following configuration as the `/etc/systemd/system/flatpak-uninstall-unused.service` file:
+
----
[Unit]
Description=Uninstall unused Flatpak runtimes
Documentation=man:flatpak

[Service]
Type=oneshot
ExecStart=/usr/bin/flatpak uninstall --unused --noninteractive
----

. Save the following configuration as the `/etc/systemd/system/flatpak-uninstall-unused.timer` file:
+
----
[Unit]
Description=Uninstall unused Flatpak runtimes once a week
Documentation=man:flatpak

[Timer]
OnCalendar=weekly
AccuracySec=1h
Persistent=true

[Install]
WantedBy=timers.target
----

. Reload systemd units:
+
----
# systemctl daemon-reload
----

. Enable the timer:
+
----
# systemctl enable --now flatpak-uninstall-unused.timer
----


== My personal dotfiles [[my-dotfiles]]

Many people keep their config files in a git repository, myself included. If you'd like to use my _dotfiles_ or just get some inspiration, see my https://gitlab.com/msuchane/dotfiles[dotfiles] repository on GitLab.

=== Guides to set up dotfiles [[dotfiles-guides]]

* link:https://dotfiles.github.io/[]
* link:https://www.gnu.org/software/stow/[]
* link:https://medium.com/@webprolific/getting-started-with-dotfiles-43c3602fd789[]
