= Configuring Ubuntu

include::attributes.adoc[]

== Hide the snap folder

The `snap` folder in your home directory is visible by default. It stores data for your snap applications. Most users don't need to access it manually.

To hide the folder:

* Create the `.hidden` file in your home directory listing the `snap` folder:
+
----
echo snap >> ~/.hidden
----


== Add more swap space

In the default installation, Ubuntu only creates a 4GB swap file. Unless your disk is very small, you probably want to add more swap space to extend the system memory.

NOTE: If your disk is slow, especially if you have a magnetic hard disk, this process might lock up your system for several minutes. Consider xref:blk-mq[setting the BFQ scheduler] before you start to prevent the issue.

. Create a blank 8 GB file:
+
[source,bash]
----
sudo dd if=/dev/zero of=/swapfile-8gb bs=1024 count=8388608
----
+
The 8388608 value represents 8GB. Alternatively, 1 GB is 1048576, which you can multiply by your preferred number of GB.

. Limit the file permissions:
+
[source,bash]
----
sudo chmod 600 /swapfile-8gb
----

. Convert the file to swap:
+
[source,bash]
----
sudo mkswap /swapfile-8gb
----

. Activate the swap file:
+
[source,bash]
----
sudo swapon /swapfile-8gb
----

. Permanently mount the swap file. Add the following line in the `/etc/fstab` file:
+
----
/swapfile-8gb	none	swap	sw	0	0
----

. Refresh systemd units:
+
[source,bash]
----
sudo systemctl daemon-reload
----

For more details, see link:https://www.howtogeek.com/455981/how-to-create-a-swap-file-on-linux/[].


== Enable Flatpak

By deault, Ubuntu doesn't support Flatpak and it doesn't come with an app store where you could manage Flatpak applications. Install both:

. Install Flatpak:
+
[source,bash]
----
sudo apt install flatpak
----

. Add the Flathub repository:
+
[source,bash]
----
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
----

. Reboot the system.

. Install the Bazaar app store:
+
[soure,bash]
----
flatpak install flathub io.github.kolunmi.Bazaar
----

. If Flatpak doesn't update applications automatically, consider adding a timer as in xref:configuring-common-linux-options.adoc#autoremove-flatpak-runtimes[].


include::debian-ubuntu-common.adoc[]
