= Configuring Debian

include::attributes.adoc[]

== Enable sudo [[sudo-config]]

. Become root the traditional way:
+
[source,bash]
----
su
----

. Install the `sudo` package:
+
[source,bash]
----
apt install sudo
----

. Add your user to the `sudo` group:
+
[source,bash,subs=+quotes]
....
usermod -a -G sudo __your_user_name__
....

. Reboot your system.

== Enable automatic updates in Debian [[debian-auto-update]]

Debian can automatically install package updates at configurable times using the Unattended Upgrades feature.

For more information, see the https://wiki.debian.org/UnattendedUpgrades[UnattendedUpgrades] page on the Debian Wiki.

== Use journald as the only logging service [[only-journald]]

By default, Debian uses `rsyslog` as the system log service. However, `journald` is running anyway all the time and there's no reason to have two log service, other than that `rsyslog` provides plain-text logs. If that doesn't sound compelling to you:

- Disable `rsyslog`:
+
[source,bash]
----
sudo systemctl disable rsyslog
----
+
- Make `journald` store its log permanently (instead of at runtime only). In `/etc/systemd/journald.conf` set:
+
----
Storage=persistent
----

== Enable command-not-found [[set-up-cnf]]

`command-not-found` is a helpful little program, which offers you to install the correct package when you type the command of a program that hasn't been installed yet. Fedora and Ubuntu do this automatically; in Debian, a little effort is needed.

. Install `command-not-found`:
+
[source,bash]
----
sudo apt install command-not-found
----

. Update the packages & commands database:
+
[source,bash]
----
sudo apt-file update
sudo update-command-not-found
----

== Enable the Plymouth boot screen

Plymouth is the pretty animated picture you see when the system is booting up or shutting down. Debian doesn't like pretty stuff by default, and therefore, Plymouth has to be installed manually.

The process is https://wiki.debian.org/plymouth[documented on the Debian Wiki]. However, to save you a few clicks and some reading:

. Install Plymouth and its themes:
+
[source,bash]
----
sudo apt install plymouth plymouth-themes
----

. Edit the `/etc/initramfs-tools/modules` and add modesetting modules for your graphics card:

** For Intel GPUs:
+
----
# KMS
intel_agp
drm
i915 modeset=1
----

** For nVidia GPUs using the Nouveau driver:
+
----
# KMS
drm
nouveau modeset=1
----

** For AMD GPUs (may be slightly outdated):
+
----
# KMS
drm
radeon modeset=1
----

. Open the `/etc/default/grub` file.

. There, uncomment the `GRUB_GFXMODE=` line and set it to your display resolution. For example, `GRUB_GFXMODE=1024x768`. (This may not be necessary and might even uglify grub; test it.)

. Also, edit the kernel line, that is the one starting with `GRUB_CMDLINE_LINUX_DEFAULT=`. Add `splash` at the end and delete `quiet` if you'd like to be able to see detailed `systemd` boot output when you switch out of the pretty animated picture.

. Save the file and update `grub2`:
+
[source,bash]
----
sudo update-grub2
----

. Get the list of installed Plymouth themes:
+
[source,bash]
----
sudo plymouth-set-default-theme -l
----
+
The default theme in Debian Stretch is `softwaves`. The rest are either the themes of earlier Debian releases or are bundled with Plymouth itself, originally coming from Fedora.

. Set a theme for Plymouth to actually use:
+
[source,bash,subs=+quotes]
....
sudo plymouth-set-default-theme -R __your_selected_theme__
....

. Reboot and watch the result. Repeat the last two steps if you want to see more themes in action.


== Enable Wayland in Firefox

On Debian 12 Bookworm, Wayland is the default GNOME session, but Firefox still runs in XWayland. This decreases graphics sharpness when you enable display scaling, for example.

To enable Wayland in Firefox, set the following shell variable:

[source,bash]
----
MOZ_ENABLE_WAYLAND=1
----

include::debian-ubuntu-common.adoc[]
