= Configuring Debian

include::attributes.adoc[]

== Enable sudo [[sudo-config]]

. Become root the traditional way:
+
[source,bash]
----
su
----

. Install the `sudo` package:
+
[source,bash]
----
apt install sudo
----

. Add your user to the `sudo` group:
+
[source,bash,subs=+quotes]
....
usermod -a -G sudo __your_user_name__
....

. Reboot your system.

== Package managers

Debian comes with several front ends to package management:

`apt`::
The default, pre-installed tool.

`aptitude`::
An advanced interface including terminal graphics.

`nala`::
An alternative to `apt` with a more readable interface and innovative features.

== Enable automatic updates in Debian [[debian-auto-update]]

Debian can automatically install package updates at configurable times using the Unattended Upgrades feature.

For more information, see the https://wiki.debian.org/UnattendedUpgrades[UnattendedUpgrades] page on the Debian Wiki.

== Use journald as the only logging service [[only-journald]]

By default, Debian uses `rsyslog` as the system log service. However, `journald` is running anyway all the time and there's no reason to have two log service, other than that `rsyslog` provides plain-text logs. If that doesn't sound compelling to you:

- Disable `rsyslog`:
+
[source,bash]
----
sudo systemctl disable rsyslog
----
+
- Make `journald` store its log permanently (instead of at runtime only). In `/etc/systemd/journald.conf` set:
+
----
Storage=persistent
----

== Enable command-not-found [[set-up-cnf]]

`command-not-found` is a helpful little program, which offers you to install the correct package when you type the command of a program that hasn't been installed yet. Fedora and Ubuntu do this automatically; in Debian, a little effort is needed.

. Install `command-not-found`:
+
[source,bash]
----
sudo apt install command-not-found
----
+
. Update the packages & commands database:
+
[source,bash]
----
sudo apt-file update
sudo update-command-not-found
----

== Periodically clean packages

By default, the `apt` package manager keeps all downloaded packages on disk indefinitely. This can result in a lot of wasted disk space.

To configure `apt` to clean outdated downloaded packages periodically every 7 days (and keep only up-to-date packages), create the `/etc/apt/apt.conf.d/02periodic` file containing:

----
APT::Periodic::AutocleanInterval "7";
----

Or to periodically clean all downloaded packages regardless of them being up-to-date or not:

----
APT::Periodic::CleanInterval "7";
----

== Enable the Plymouth boot screen

Plymouth is the pretty animated picture you see when the system is booting up or shutting down. Debian doesn't like pretty stuff by default, and therefore, Plymouth has to be installed manually.

The process is https://wiki.debian.org/plymouth[documented on the Debian Wiki]. However, to save you a few clicks and some reading:

. Install Plymouth and its themes:
+
[source,bash]
----
sudo apt install plymouth plymouth-themes
----

. Edit the `/etc/initramfs-tools/modules` and add modesetting modules for your graphics card:

** For Intel GPUs:
+
----
# KMS
intel_agp
drm
i915 modeset=1
----

** For nVidia GPUs using the Nouveau driver:
+
----
# KMS
drm
nouveau modeset=1
----

** For AMD GPUs (may be slightly outdated):
+
----
# KMS
drm
radeon modeset=1
----


. Open the `/etc/default/grub` file.

. There, uncomment the `GRUB_GFXMODE=` line and set it to your display resolution. For example, `GRUB_GFXMODE=1024x768`. (This may not be necessary and might even uglify grub; test it.)

. Also, edit the kernel line, that is the one starting with `GRUB_CMDLINE_LINUX_DEFAULT=`. Add `splash` at the end and delete `quiet` if you'd like to be able to see detailed `systemd` boot output when you switch out of the pretty animated picture.

. Save the file and update `grub2`:
+
[source,bash]
----
sudo update-grub2
----

. Get the list of installed Plymouth themes:
+
[source,bash]
----
sudo plymouth-set-default-theme -l
----
+
The default theme in Debian Stretch is `softwaves`. The rest are either the themes of earlier Debian releases or are bundled with Plymouth itself, originally coming from Fedora.

. Set a theme for Plymouth to actually use:
+
[source,bash,subs=+quotes]
....
sudo plymouth-set-default-theme -R __your_selected_theme__
....

. Reboot and watch the result. Repeat the last two steps if you want to see more themes in action.


== Install additional packages [[debian-packages]]

=== Enable package repositories

To have access to all packages listed here, enable the _Contrib_ and _Non-free_ Debian repositories. This is done by editing the `/etc/apt/sources.list` file.

Here's a sample `sources.list` for Debian Stretch, configured to include all repositories and to download data from the primary Czech server:

----
# Basic repositories
deb http://ftp.cz.debian.org/debian/ stretch main contrib non-free

# Debian Stretch updates
deb http://ftp.cz.debian.org/debian/ stretch-updates main contrib non-free

# Debian Stretch security updates
deb http://security.debian.org/ stretch/updates main contrib non-free

# Debian Stretch backports -- the '-t stretch-backports' option
# has to be specified explicitly to install packages from backports
deb http://ftp.cz.debian.org/debian stretch-backports main contrib non-free
----

Alternatively, you can also use the https://deb.debian.org/[deb.debian.org] service, which automatically determines the fastest server for you each time `apt` downloads data:

----
# Basic repositories
deb http://deb.debian.org/debian/ stretch main contrib non-free

# Debian Stretch updates
deb http://deb.debian.org/debian/ stretch-updates main contrib non-free

# Debian Stretch security updates
deb http://deb.debian.org/debian-security stretch/updates main contrib non-free

# Debian Stretch backports -- the '-t stretch-backports' option
# has to be specified explicitly to install packages from backports
deb http://deb.debian.org/debian stretch-backports main contrib non-free
----

Further references:

- https://wiki.debian.org/SourcesList[A sources.list article on the Debian Wiki]
- https://www.debian.org/mirror/list[Debian mirror list]
- https://debgen.simplylinux.ch/[A sources.list generator]
- https://wiki.debian.org/Backports[Debian backports] – install fresh packages on Debian Stable

=== Multimedia [[debian-multimedia]]

[source,bash]
----
$ apt install \
audacity beets cuetools easytag exfalso flac gimp gnome-backgrounds \
gnome-mpv gnome-music gnome-photos gnome-sound-recorder \
gstreamer1.0-libav gstreamer1.0-packagekit gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-ugly inkscape kde-wallpapers kdeartwork-wallpapers \
kdenlive krita lame libva-drm1 libva-egl1 libva-intel-vaapi-driver \
libva1 libvdpau-va-gl1 libvdpau1 libvulkan1 mcomix mediainfo \
mesa-vdpau-drivers mesa-vulkan-drivers mpv opus-tools quodlibet \
shntool sox vdpauinfo vlc vorbis-tools vulkan-utils youtube-dl \
----

=== Office, Reading and Writing [[debian-read-write]]

[source,bash]
----
$ apt install \
bijiben fbreader gedit-plugins gnome-calendar gnome-dictionary \
gnome-todo gnome-shell-extensions-gpaste libreoffice-style-sifr \
nano neovim pandoc scribus simple-scan vim-nox
----

=== Other Applications [[debian-other-apps]]

[source,bash]
----
$ apt install \
brasero chromium dconf-editor epiphany-browser gnome-builder \
gnome-logs gnome-maps gnome-nettool gnome-packagekit \
gnome-power-manager gnome-tweak-tool tracker-gui transmission-gtk
----

=== Archiving and File Systems [[debian-archiving-fs]]

[source,bash]
----
$ apt install \
atool bleachbit borgbackup exfat-fuse exfat-utils f2fs-tools \
hfsplus hfsutils lzip lziprecover lzop \
p7zip-full progress testdisk udftools unrar xfsdump \
zfs-dkms zfs-initramfs zfsutils-linux 
----

=== Various Low-level Stuff [[debian-various-ll]]

[source,bash]
----
$ apt install \
amd64-microcode beignet-opencl-icd clinfo earlyoom firmware-amd-graphics \
firmware-atheros firmware-brcm80211 firmware-ipw2x00 \
firmware-iwlwifi firmware-linux firmware-linux-free \
firmware-linux-nonfree firmware-misc-nonfree firmware-realtek \
fish htop intel-microcode iftop iotop iucode-tool mc nala powertop \
sudo tlp zsh
----

=== Czech Localization [[debian-czech-l10n]]

[source,bash]
----
$ apt install \
chromium-l10n firefox-esr-l10n-cs hyphen-cs libreoffice-help-cs \
libreoffice-l10n-cs 
----

=== Fonts [[debian-fonts]]

[source,bash]
----
$ apt install \
fonts-cabin fonts-cabinsketch fonts-cantarell \
fonts-croscore fonts-crosextra-caladea fonts-crosextra-carlito \
fonts-fanwood fonts-firacode fonts-inconsolata fonts-isabella \
fonts-larabie-deco fonts-larabie-uncommon fonts-lato \
fonts-liberation2 fonts-linuxlibertine fonts-hack-otf \
fonts-noto-hinted fonts-noto-mono \
fonts-oldstandard fonts-opendyslexic fonts-open-sans fonts-quattrocento \
fonts-roboto-hinted fonts-sil-gentiumplus fonts-symbola \
ttf-anonymous-pro ttf-essays1743
----

=== Games and Game-related [[debian-games]]

[source,bash]
----
$ apt install \
0ad astromenace blobwars bsdgames crawl crawl-tiles endless-sky fillets-ng \
freecol freeciv frozen-bubble gnome-2048 gnome-games hedgewars \
libtxc-dxtn-s2tc libtxc-dxtn-s2tc-bin lierolibre neverball \
sauerbraten wesnoth
----

=== See also

- https://flathub.org/apps.html[Flathub]
- https://flatpak.org/apps.html[Flatpak Applications]
