// This is a snippet with content shared between Debian and Ubuntu.

== Enable the firewall

. Install the Uncomplicated Firewall (UFW) service:
+
[source,bash]
----
sudo apt install ufw
----

. Check the firewall status:
+
[source,bash]
----
sudo ufw status
----

. Allow SSH access if you want to use SSH:
+
[source,bash]
----
sudo ufw allow ssh
----
+
NOTE: Consider allowing SSH on a different port or allowing other connections, too. For more information, see link:https://www.cyberciti.biz/faq/set-up-a-firewall-with-ufw-on-debian-12-linux/[].

. Enable UFW:
+
[source,bash]
----
sudo ufw enable
----


== Package managers

Debian comes with several front ends to package management:

`apt`::
The default, pre-installed tool.

`aptitude`::
An advanced interface including terminal graphics.

`nala`::
An alternative to `apt` with a more readable interface and innovative features.


== Periodically clean packages

By default, the `apt` package manager keeps all downloaded packages on disk indefinitely. This can result in a lot of wasted disk space.

To configure `apt` to clean outdated downloaded packages periodically every 7 days (and keep only up-to-date packages), create the `/etc/apt/apt.conf.d/02periodic` file containing:

----
APT::Periodic::AutocleanInterval "7";
----

Or to periodically clean all downloaded packages regardless of them being up-to-date or not:

----
APT::Periodic::CleanInterval "7";
----


== Enable 32-bit applications

By default, the 64-bit, `amd64` Debian installation doesn't enable installing 32-bit programs and the libraries that they depend on. This prevents installing applications like Steam.

. Enable the 32-bit compatibility repository:
+
[source,bash]
----
sudo dpkg --add-architecture i386
----

. Refresh the repository metadata:
+
[source,bash]
----
sudo apt update
----

. You can now install 32-bit programs.

For details, see link:https://wiki.debian.org/Multiarch/HOWTO[Multiarch].


== Install additional packages [[debian-packages]]

=== Office, reading, and writing [[debian-read-write]]

[source,bash]
----
sudo apt install \
  bijiben endeavour fbreader gnome-calendar gnome-dictionary \
  gnome-shell-extensions-gpaste micro \
  nano neovim pandoc scribus simple-scan
----

=== Other applications [[debian-other-apps]]

[source,bash]
----
sudo apt install \
  chromium dconf-editor epiphany-browser gnome-builder \
  gnome-logs gnome-maps gnome-nettool \
  gnome-power-manager gnome-tweaks transmission-gtk
----
