// This is a snippet with content shared between Debian and Ubuntu.

== Package managers

Debian comes with several front ends to package management:

`apt`::
The default, pre-installed tool.

`aptitude`::
An advanced interface including terminal graphics.

`nala`::
An alternative to `apt` with a more readable interface and innovative features.

== Periodically clean packages

By default, the `apt` package manager keeps all downloaded packages on disk indefinitely. This can result in a lot of wasted disk space.

To configure `apt` to clean outdated downloaded packages periodically every 7 days (and keep only up-to-date packages), create the `/etc/apt/apt.conf.d/02periodic` file containing:

----
APT::Periodic::AutocleanInterval "7";
----

Or to periodically clean all downloaded packages regardless of them being up-to-date or not:

----
APT::Periodic::CleanInterval "7";
----

== Enable 32-bit applications

By default, the 64-bit, `amd64` Debian installation doesn't enable installing 32-bit programs and the libraries that they depend on. This prevents installing applications like Steam.

. Enable the 32-bit compatibility repository:
+
[source,bash]
----
sudo dpkg --add-architecture i386
----

. Refresh the repository metadata:
+
[source,bash]
----
sudo apt update
----

. You can now install 32-bit programs.

For details, see link:https://wiki.debian.org/Multiarch/HOWTO[Multiarch].


== Install additional packages [[debian-packages]]

=== Multimedia [[debian-multimedia]]

[source,bash]
----
sudo apt install \
audacity beets cuetools easytag exfalso flac gimp gnome-backgrounds \
gnome-mpv gnome-music gnome-photos gnome-sound-recorder \
gstreamer1.0-libav gstreamer1.0-packagekit gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-ugly inkscape kde-wallpapers kdeartwork-wallpapers \
kdenlive krita lame libva-drm1 libva-egl1 libva-intel-vaapi-driver \
libva1 libvdpau-va-gl1 libvdpau1 libvulkan1 mcomix mediainfo \
mesa-vdpau-drivers mesa-vulkan-drivers mpv opus-tools quodlibet \
shntool sox vdpauinfo vlc vorbis-tools vulkan-utils youtube-dl \
----

=== Office, reading, and writing [[debian-read-write]]

[source,bash]
----
sudo apt install \
bijiben fbreader gedit-plugins gnome-calendar gnome-dictionary \
gnome-todo gnome-shell-extensions-gpaste libreoffice-style-sifr \
nano neovim pandoc scribus simple-scan vim-nox
----

=== Other applications [[debian-other-apps]]

[source,bash]
----
sudo apt install \
brasero chromium dconf-editor epiphany-browser gnome-builder \
gnome-logs gnome-maps gnome-nettool gnome-packagekit \
gnome-power-manager gnome-tweak-tool tracker-gui transmission-gtk
----

=== Archiving and file systems [[debian-archiving-fs]]

[source,bash]
----
sudo apt install \
atool bleachbit borgbackup exfat-fuse exfat-utils f2fs-tools \
hfsplus hfsutils lzip lziprecover lzop \
p7zip-full progress testdisk udftools unrar xfsdump \
zfs-dkms zfs-initramfs zfsutils-linux 
----

=== Low-level tools [[debian-various-ll]]

[source,bash]
----
sudo apt install \
amd64-microcode beignet-opencl-icd clinfo earlyoom firmware-amd-graphics \
firmware-atheros firmware-brcm80211 firmware-ipw2x00 \
firmware-iwlwifi firmware-linux firmware-linux-free \
firmware-linux-nonfree firmware-misc-nonfree firmware-realtek \
fish htop intel-microcode iftop iotop iucode-tool mc nala powertop \
sudo tlp zsh
----

=== Czech localization [[debian-czech-l10n]]

[source,bash]
----
sudo apt install \
chromium-l10n firefox-esr-l10n-cs hyphen-cs libreoffice-help-cs \
libreoffice-l10n-cs 
----

=== Fonts [[debian-fonts]]

[source,bash]
----
sudo apt install \
fonts-cabin fonts-cabinsketch fonts-cantarell \
fonts-croscore fonts-crosextra-caladea fonts-crosextra-carlito \
fonts-fanwood fonts-firacode fonts-inconsolata fonts-isabella \
fonts-larabie-deco fonts-larabie-uncommon fonts-lato \
fonts-liberation2 fonts-linuxlibertine fonts-hack-otf \
fonts-noto-hinted fonts-noto-mono \
fonts-oldstandard fonts-opendyslexic fonts-open-sans fonts-quattrocento \
fonts-roboto-hinted fonts-sil-gentiumplus fonts-symbola \
ttf-anonymous-pro ttf-essays1743
----

=== Games and related [[debian-games]]

[source,bash]
----
sudo apt install \
0ad astromenace blobwars bsdgames crawl crawl-tiles endless-sky fillets-ng \
freecol freeciv frozen-bubble gnome-2048 gnome-games hedgewars \
libtxc-dxtn-s2tc libtxc-dxtn-s2tc-bin lierolibre neverball \
sauerbraten wesnoth
----
