= Configuring GNOME [[gnome]]

include::attributes.adoc[]
:experimental:

== Install GNOME Shell extensions

The official method to install Shell extensions is through the link:https://extensions.gnome.org/[extensions.gnome.org] web interface. However, it depends on browser integration that might be tricky to set up correctly.

Instead, you can use the Extension Manager application, which enables you to manage and install Shell extensions on your system.

* Install on Debian and Ubuntu:
+
[source,bash]
----
sudo apt install gnome-shell-extension-manager
----

* Install from Flatpak: link:https://flathub.org/apps/details/com.mattjakeman.ExtensionManager[com.mattjakeman.ExtensionManager]

=== Selected GNOME Shell extensions [[gs-extensions]]

link:https://extensions.gnome.org/extension/307/dash-to-dock/[Dash to Dock]::
Makes the left-hand-side applications panel accessible even when the Activities overview isn't active.

link:https://extensions.gnome.org/extension/1160/dash-to-panel/[Dash to Panel]::
Similar to Dash to Dock, but creates a Windows-like panel instead.

link:https://extensions.gnome.org/extension/615/appindicator-support/[AppIndicator and KStatusNotifierItem Support]::
Displays tray icons in the top panel.

=== Enable clipboard history

By default, you can only copy and paste one item at a time. With several extensions to GNOME Shell, you can switch to previously copied items.

* link:https://extensions.gnome.org/extension/4839/clipboard-history/[Clipboard History by SUPERCILEX]

* link:https://extensions.gnome.org/extension/8834/copyous/[Copyous by boerdereinar]


== Increase sound volume above 100% [[sound-over-amplification]]

In earlier versions of GNOME, you could enable volume over-amplification in GNOME Tweaks. The configuration is now in menu:Settings[Sound].

Alternatively, you can enable over-amplification using `gsettings`:

[source,bash]
----
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
----


== Configure the Nautilus drag-and-drop behavior [[nautilus-dnd]]

Nautilus (_Files_) opens directories when you hover a dragged item over them. Personally, I don't like this behavior, because it requires me to be quick and precise, which I'm not. Therefore, to disable the automatic folder opening:

[source,bash]
----
dconf write \
/org/gnome/nautilus/preferences/open-folder-on-dnd-hover \
false
----


== Enable the Compose key [[compose-key]]

The Compose key allows you to combine a couple of characters on your keyboard to type exotic characters and diacritics. Available combinations are listed in the https://help.ubuntu.com/community/GtkComposeTable[GtkComposeTable] article on the Ubuntu Community Help Wiki.

You can configure your Compose key in menu:Settings[Keyboard]. Set it to a key you only rarely use, for example the kbd:[Menu] key or kbd:[PrintScreen].

To set the Compose key to the kbd:[Menu], kbd:[PrintScreen], and kbd:[Right Win] keys (missing keys are ignored), you can also use `dconf`:

[source,bash]
----
dconf write \
/org/gnome/desktop/input-sources/xkb-options \
"['compose:menu', 'compose:prsc', 'compose:rwin']"
----

NOTE: This command rewrites your keyboard preferences from Settings.

Starting with version 3.20, GTK can read traditional XLib Compose configuration files. You can configure your own composition rules this way, storing them in the `~/.config/gtk-3.0/Compose` or `~/.XCompose` files. For more information, see _Defining custom Compose sequences_ in the http://blog.cyberborean.org/2008/01/06/compose-key-magic[Compose key magic] article on the Cyberborean Chronicles blog.


== Configure the window switching shortcuts [[win-switching]]

By default, both the kbd:[Alt + Tab] and the kbd:[Win + Tab] key (and their kbd:[Shift] variants) switch _applications_ in Gnome. Sometimes, you want to switch between _windows_ instead.

You can configure kbd:[Win + Tab] to only switch between applications and kbd:[Alt + Tab] to only switch between windows:

[source,bash]
----
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab']"

gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Super>Tab']"

gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"

gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Shift><Alt>Tab']"
----

The resulting behavior is consistent with both Windows (window-switching with kbd:[Alt + Tab]) and Mac (application-switching with kbd:[Cmd + Tab]).


== Block ads in Epiphany [[epiphany-adblock]]

The _Epiphany_ web browser, also called _Web_ or _WWW_, blocks ads by default. However, the blocking list is rather limited. New lists can be added by changing the `/org/gnome/epiphany/adblock-filters` DConf key.

For example, to block tracking, social-networks elements, anti-adblock pop-ups, and Czech/Slovak ads:

[source,bash]
----
gsettings set \
org.gnome.epiphany adblock-filters \
"['https://easylist.to/easylist/easylist.txt', \
'https://easylist.to/easylist/easyprivacy.txt', \
'https://easylist.to/easylist/fanboy-social.txt', \
'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt', \
'https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt']"
----


== Limit the load of file metadata mining [[tracker-preferences]]

GNOME includes the Tracker service to extract file metadata and provide a search database. This might slow down the system if you have a slow hard disk.

Consider browsing the following paths in the DConf Editor:

* `/org/freedesktop/tracker/`
* `/org/freedesktop/tracker/extract/`
* `/org/freedesktop/tracker/miner/files/`


== View and edit files as root in GNOME [[gui-root-edit]]

=== In Files

In the *Files* application, you can open any directory with root permissions. This has been available since Gnome 3.24. To do that:

. In  *Files*, activate the directory path field, for example by pressing kbd:[Ctrl+L].

. Type the following into the field:
+
[subs=+quotes]
----
admin:///_directory-path_/
----
+
Replace _directory-path_ with the path to the directory that you want to access. Note that there are three slashes at the beginning, the third of which stands for the root directory in the absolute path; the slash after the path is also required. For example, to access the `/etc/default/` directory, type `admin:///etc/default/`.

. Enter your password in the prompt that shows up.

Applications launched from the *Files* window can also inherit the same root privileges.

=== In text editors and other applications

Graphical text editors that use the `gvfs` GNOME infrastructure, such as Gedit, Geany, or Gnome Builder, can natively edit with root permissions.

To use this feature:

. In the editor, open the file chooser dialog, for example by pressing kbd:[Ctrl+O].
. In the dialog, activate the directory path field, for example by pressing kbd:[Ctrl+L].
. Use the method described in the previous section to open the directory that contains the file you want to edit as root.
. Select the file to edit in the file chooser.
