image:
  name: antora/antora
pages:
  stage: deploy
  interruptible: true
  script:
  - antora --fetch --redirect-facility=gitlab --to-dir=public antora-playbook.yml
  # By default, the public content is nested into an extra directory:
  # - ln -s public/linux-notes/index.html public/index.html
  artifacts:
    paths:
    - public
  only:
  - main

