image: asciidoctor/docker-asciidoctor:latest

pages:
  stage: deploy
  script:
  - asciidoctor --safe -v -n single-page.adoc -o public/index.html
  artifacts:
    paths:
    - public
  only:
  - main
