image:
  name: antora/antora
pages:
  stage: deploy
  interruptible: true
  script:
  - antora --fetch --redirect-facility=gitlab --to-dir=public antora-playbook.yml
  # By default, the public content is nested into an extra directory:
  - mv public/linux-notes/* public/
  artifacts:
    paths:
    - public
  only:
  - main

