= Applications Tuning [[applications]]
:author: Marek Suchánek
:email: marek.suchanek@protonmail.com
//:source-highlighter: highlightjs
:source-highlighter: prettify
:sectnums:
:toc:

== Firefox [[firefox]]

=== Enable Acceleration [[firefox-accel]]

Hardware acceleration in Firefox is still marked as experimental on Linux because some graphics drivers are buggy. However, you can try if it works OK on your configuration. Potentially, the benefits are smoother browsing and lower CPU usage for video playback.

To enable acceleration, set the following keys on the `about:config` page to `true`:

* `layers.acceleration.force-enabled`
* `media.hardware-video-decoding.force-enabled`
* `gfx.canvas.azure.accelerated` – Create this one if it doesn't exist.

To verify, open the `about:support` page and take a look at the _Graphics_ section.

=== Web Pages and Interface Scaling [[web-scaling]]

Depending on the pixel density (DPI) of your display, your eyesight, and the distance between you and the display, text on the web might be too small. There are multiple ways to deal with it:

* some people just zoom any web page as soon as they visit it;

* other people increase the minimal font size in settings;

* the _smartest_ people adjust the CSS pixels scaling ratio.

The benefit of the last approach is that the scaling is:

* automatic: no need to zoom by hand;

* transparent and consistent: all pages and their elements and even the Firefox interface itself are scaled by the same factor.

To utilize this great setting, go to the `about:config` page and set the following key to a comfortable value, e.g. `1.5`:

* `layout.css.devPixelsPerPx`

=== No Middle Mouse Button Paste [[middle-mouse-paste]]

By default, Firefox recognizes the middle mouse button (mouse-wheel click) the traditional UNIX way, that is it pastes clipboard content or, worse yet, loads URL from clipboard. This is surprising to all people except the two bearded sysadmins still alive today who frequent Root.cz.

To turn off middle mouse clipboard pasting, go to `about:config` in Firefox and set the following keys to `false`:

- `middlemouse.paste`
- `middlemouse.contentLoadURL`

=== No Alt Main Menu [[alt-menu]]

When you press the `Alt` key in Firefox, the main menu bar jumps at you from the top of the window. This may be convenient to you if you're used to the bar, but it hapens way too often unintentionally when pressing keyboard shortcuts.

To disable the `Alt` key menu activation, open `about:config` in Firefox and change the following key to `0`:

- `ui.key.menuAccessKey`

`18` represents `Alt` here; `17` stands for `Ctrl` if you're interested.

=== Session Back-up interval [[session-interval]]

There is a time interval setting in Firefox, which controls how often the content of the current session (tabs, etc.) is saved to disk to be able to recover in case of a crash. The default value is 15 seconds. This can lead to excessive disk writes, but that's only relevant on Windows and only harmful on SSDs, so there's probably no reason to worry about this.

Nevertheless, if you're a heavy tabs user, you might want to consider lowering the load on your system a bit. To change the interval to 5 minutes, go to `about:config` and set the following key to `300000`:

- `browser.sessionstore.interval`

This issue was brought up in the https://forums.servethehome.com/index.php?threads/firefox-is-chewing-through-your-nand.11346/[STH forums].

=== Using the Native PDF Application [[firefox-pdf]]

The built-in PDF viewer that Firefox uses is nice, but it lacks some features to display all PDFs correctly and tends to be rather heavy-weight due to being written in JavaScript.

On a low-memory system, you may consider configuring Firefox to always open your native PDF viewer instead. To do that, open Preferences, find the Applications section, search for `pdf`, and for the item that appears in the results box, change the "Action" to "Use Document Viewer".

See also the Mozilla documentation article: https://support.mozilla.org/en-US/kb/disable-built-pdf-viewer-and-use-another-viewer[How to disable the built-in PDF viewer and use another viewer]

== Gimp [[gimp]]

=== Font Aliasing [[gimp-font-alias]]

The way Gimp renders text and anti-aliases fonts is configurable. This is useful because Gimp tends to apply RGB anti-alias and https://plus.google.com/+WorldofGnomeOrg/posts/QjR629U6HQd[produce weird colorful lines] around letters.

To set a font configuration that is sensible for image editors, create the `/etc/gimp/2.0/fonts.conf` file and put there:

[source,xml]
----
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <edit name="antialias" mode="assign">
      <bool>true</bool>
    </edit>
  </match>
  <match target="font">
    <edit name="hinting" mode="assign">
      <bool>true</bool>
    </edit>
  </match>
  <match target="font">
    <edit name="hintstyle" mode="assign">
      <const>hintslight</const>
    </edit>
  </match>
  <match target="font">
    <edit name="rgba" mode="assign">
      <const>none</const>
    </edit>
  </match>
</fontconfig>
----

== Chromium and Google Chrome [[chromium]]

=== UI Scaling [[chromium-scaling]]

To scale Chromium UI on high-DPI displays:

. Install the `menulibre` application.

. In `menulibre`, navigate to Internet -> Chromium Web Browser.

. Edit the *Command* field to include the `--high-dpi-support=1` and `--force-device-scale-factor=__my-scale-factor__` scaling options:
+
[subs=+quotes]
----
/usr/bin/chromium-browser --high-dpi-support=1 --force-device-scale-factor=__my-scale-factor__ %U
----
+
Replace _my-scaling-factor_ with a floating-point number specifying how much to scale the UI. For example, use `1.25` to scale the UI to 125%.

. Similarly, edit the commands in all entries under the *Actions* tab below.

. Press *Ctrl-S* to save the launcher.

. Restart all your Chromium windows for the setting to take effect.

