= Applications Tuning [[applications]]

== Firefox [[firefox]]

=== No Middle Mouse Button Paste [[middle-mouse-paste]]

By default, Firefox recognizes the middle mouse button (mouse-wheel click) the traditional UNIX way, that is it pastes clipboard content or, worse yet, loads URL from clipboard. This is surprising to all people except the two bearded sysadmins still alive today who frequent Root.cz.

To turn off middle mouse clipboard pasting, go to `about:config` in Firefox and the following keys to `false`:

- `middlemouse.paste`
- `middlemouse.contentLoadURL`

=== No Alt Main Menu [[alt-menu]]

When you press the `Alt` key in Firefox, the main menu bar jumps at you from the top of the window. This may be convenient to you if you're used to the bar, but it hapens way too often unintentionally when pressing keyboard shortcuts.

To disable the `Alt` key menu activation, open `about:config` in Firefox and change the following key to `0`:

- `ui.key.menuAccessKey`

`18` represents `Alt` here; `17` stands for `Ctrl` if you're interested.

=== Session Back-up interval [[session-interval]]

There is a time interval setting in Firefox, which controls how often the content of the current session (tabs, etc.) is saved to disk to be able to recover in case of a crash. The default value is 15 seconds. This can lead to excessive disk writes, but that's only relevant on Windows and only harmful on SSDs, so there's probably no reason to worry about this.

Nevertheless, if you're a heavy tabs user, you might want to consider lowering the load on your system a bit. To change the interval to 5 minutes, go to `about:config` and set the following key to `300000`:

- browser.sessionstore.interval

This issue was brought up in the https://forums.servethehome.com/index.php?threads/firefox-is-chewing-through-your-nand.11346/[STH forums].


== Gimp

=== Font Aliasing

The way Gimp renders text and anti-aliases fonts is configurable. This is useful because Gimp tends to apply RGB anti-alias and https://plus.google.com/+WorldofGnomeOrg/posts/QjR629U6HQd[produce weird colorful lines] around letters.

To set a font configuration that is sensible for image editors, create the `/etc/gimp/2.0/fonts.conf` file and put there:

[source,xml]
----
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <edit name="antialias" mode="assign">
      <bool>true</bool>
    </edit>
  </match>
  <match target="font">
    <edit name="hinting" mode="assign">
      <bool>true</bool>
    </edit>
  </match>
  <match target="font">
    <edit name="hintstyle" mode="assign">
      <const>hintslight</const>
    </edit>
  </match>
  <match target="font">
    <edit name="rgba" mode="assign">
      <const>none</const>
    </edit>
  </match>
</fontconfig>
----

