= Gnome [[gnome]]
:author: Marek Suchánek
:email: marek.suchanek@protonmail.com
//:source-highlighter: highlightjs
:source-highlighter: prettify
:sectnums:
:toc:

== Battery Percentage Indicator [[battery-percent]]

To show battery percentage in the top panel, change the `org.gnome.desktop.interface.show-battery-percentage` dconf key:

[source,bash,subs=+quotes]
----
dconf write \
/org/gnome/desktop/interface/show-battery-percentage \
true
----

== Night Light Temperature [[night-temp]]

To change the Night Light temperature in Gnome 3.24 (newer versions should include a GUI setting), set the `org.gnome.settings-daemon.plugins.color.night-light-temperature` key to your desired temperature. For example, for 4,500 degrees Kelvin:

[source,bash,subs=+quotes]
----
dconf write \
/org/gnome/settings-daemon/plugins/color/night-light-temperature \
4500
----

== Nautilus Drag-and-Drop Behavior [[nautilus-dnd]]

Nautilus ("Files") opens directories when you hover a dragged item over them. Personally, I don't like this behavior, because it requires me to be quick and precise, which I'm not. Therefore, to disable the automatic folder opening:

[source,bash]
----
dconf write \
/org/gnome/nautilus/preferences/open-folder-on-dnd-hover \
false
----

== Backing Up dconf Settings [[dconf-backup]]

`dconf` settings cannot be copied over to another system or to another user like regular, plain-text files. However, you can export ("dump") them to a text file and then import ("load") them from it again:

[source,bash,subs=+quotes]
----
dconf dump /__path/to/export/__ > __exported-dconf-settings.txt__
dconf load /__path/to/import/__ < __exported-dconf-settings.txt__
----

For example:

[source,bash]
----
dconf dump /org/gnome/ > gnome-dconf-settings.txt
dconf load /org/gnome/ < gnome-dconf-settings.txt
----

== Configuring the Compose Key [[compose-key]]

The Compose key allows you to combine a couple of characters on your keyboard to type exotic characters and diacritics. Available combinations are listed in the https://help.ubuntu.com/community/GtkComposeTable[GtkComposeTable] article on the Ubuntu Community Help Wiki.

You can configure your Compose key using the Tweak Tool in the Typing tab. Set it to a key you only rarely use, for example the Menu key or PrintScreen.

To set the Compose key to the Menu, PrintScreen, and Right Win keys (missing keys are ignored), you might also use `dconf`:

[source,bash]
----
dconf write \
/org/gnome/desktop/input-sources/xkb-options \
"['compose:menu', 'compose:prsc', 'compose:rwin']"
----

NOTE: This command rewrites all your Typing preferences you set in the Tweak Tool.

Starting with version 3.20, GTK can read traditional XLib Compose configuration files. You can configure your own composition rules this way, storing them in the `~/.config/gtk-3.0/Compose` or `~/.XCompose` files. For more information, see _Defining custom Compose sequences_ in the http://blog.cyberborean.org/2008/01/06/compose-key-magic[Compose key magic] article on the Cyberborean Chronicles blog.

== Window Switching Shortcuts [[win-switching]]

By default, both the `Alt`-`Tab` and the `Win`-`tab` key (and their `Shift` variants) switch _applications_ in Gnome. This is a matter of taste, but sometimes, you want to simply switch _windows_ instead. A common use case is when an application uses more than one window.

To keep an application-switching shortcut but add a window-switching one as well, configure `Win`-`Tab` to only switch between applications and `Alt`-`Tab` to only switch between windows:

[source,bash]
----
dconf write \
/org/gnome/desktop/wm/keybindings/switch-applications \
"['<Super>Tab']"

dconf write \
/org/gnome/desktop/wm/keybindings/switch-applications-backward \
"['<Shift><Super>Tab']"

dconf write \
/org/gnome/desktop/wm/keybindings/switch-windows \
"['<Alt>Tab']"

dconf write \
/org/gnome/desktop/wm/keybindings/switch-windows-backward \
"['<Shift><Alt>Tab']"
----

As an added bonus, the resulting behavior is consistent with both Windows (window-switching with `Alt`-`Tab`) and Mac (application-switching with `Cmd`-`Tab`).

== Lock Down DConf [[dconf-lockdown]]

Gnome offers ways to https://help.gnome.org/admin/system-admin-guide/stable/user-settings.html.en#lockdown[lock down certain aspects of the user interface]. This is useful when untrusted or unqualified people are expected to use the computer; for example, when setting up an internet kiosk, a public library PC, or when kids are around.

To prevent specific DConf keys from being modified (to lock them down), follow the official Gnome documentation in the https://help.gnome.org/admin/system-admin-guide/stable/dconf-lockdown.html.en[Lock down specific settings] article.

== Epiphany Adblock Lists [[epiphany-adblock]]

The _Epiphany_ web browser, also called _Web_ or _WWW_, blocks ads by default. However, the blocking list is rather limited. New lists can be added by changing the `/org/gnome/epiphany/adblock-filters` DConf key.

For example, to block tracking, social-networks elements, anti-adblock pop-ups, and Czech/Slovak ads:

[source,bash]
----
dconf write \
/org/gnome/epiphany/adblock-filters \
"['https://easylist.to/easylist/easylist.txt', \
'https://easylist.to/easylist/easyprivacy.txt', \
'https://easylist.to/easylist/fanboy-social.txt', \
'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt', \
'https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt']"
----

== Fractional Scaling [[fractional-scaling]]

Currently (v3.26), Gnome and the GTK+ toolkit allow interface scaling by integers only by default. That is, by the factor of 1.0, 2.0, etc. If you're using a screen that has a semi-high pixel density, neither of these settings work very well and your user interface elements look either too small or too big.

However, in 3.26, a new, experimental option has been introduced to allow fractional, non-integer scaling: for example, 1.25× or 1.5×. It doesn't work that great yet but you can try it out to see what it's like. You need to set the `/org/gnome/mutter/experimental-features` DConf key and do a little config dance:

. Enable the experimental feature in DConf:
+
[source,bash]
----
dconf write \
/org/gnome/mutter/experimental-features \
"['scale-monitor-framebuffer']"
----

. Log out of Gnome and log back in again.

. Go to Gnome Settings → Devices → Displays and select a "Scale" value that you're comfortable with. You can set a different scaling factor for each of your displays.

If you decide to disable the feature and go back to integer scaling, unset the key:

[source,bash]
----
dconf reset \
/org/gnome/mutter/experimental-features
----

NOTE: For now, a reasonable alternative to fractional scaling is to scale just the fonts. Use the "Scaling Factor" in the "Fonts" tab in Tweaks. Additionally, you may want to set a similar value for Firefox to scale CSS. See the Applications chapter, Firefox section for more information.

== Some Gnome Shell Extensions [[gs-extensions]]

https://extensions.gnome.org/extension/307/dash-to-dock/[Dash to Dock] :: Makes the left-hand-side applications panel accessible even when the Activities overview isn't active.
https://extensions.gnome.org/extension/1160/dash-to-panel/[Dash to Panel] :: Similar to Dash to Dock, but creates a Windows-like panel instead.
Gpaste :: Manages the clipboard (selectable history of copy-and-paste). Install from distribution packages: `gnome-shell-extension-gpaste` in Fedora and `gnome-shell-extensions-gpaste` in Debian.
https://extensions.gnome.org/extension/723/pixel-saver/[Pixel Saver] :: Hides the titlebar of maximized windows that don't use a headerbar.
https://extensions.gnome.org/extension/495/topicons/[TopIcons] or https://extensions.gnome.org/extension/1031/topicons/[TopIcons Plus] :: Displays tray icons in the top panel.

