= Gnome [[gnome]]

== Battery Percentage Indicator [[battery-percent]]

To show battery percentage in the top panel, change the `org.gnome.desktop.interface.show-battery-percentage` dconf key:

    dconf write /org/gnome/desktop/interface/show-battery-percentage true

== Night Light Temperature [[night-temp]]

To change the Night Light temperature in Gnome 3.24 (newer versions should include a GUI setting), set the `org.gnome.settings-daemon.plugins.color.night-light-temperature` key to your desired temperature. For example, for 4,500 degrees Kelvin:

    dconf write /org/gnome/settings-daemon/plugins/color/night-light-temperature 4500

== Nautilus Drag-and-Drop Behavior [[nautilus-dnd]]

Nautilus ("Files") opens directories when you hover a dragged item over them. Personally, I don't like this behavior, because it requires me to be quick and precise, which I'm not. Therefore, to disable the automatic folder opening:

    dconf write /org/gnome/nautilus/preferences/open-folder-on-dnd-hover false

== Backing Up dconf Settings [[dconf-backup]]

`dconf` settings cannot be copied over to another system or to another user like regular, plain-text files. However, you can export ("dump") them to a text file and then import ("load") them from it again:

    dconf dump /path/to/export/ > exported-dconf-settings.txt
    dconf load /path/to/import/ < exported-dconf-settings.txt

For example:

    dconf dump /org/gnome/ > gnome-dconf-settings.txt
    dconf load /org/gnome/ < gnome-dconf-settings.txt

