= Gnome [[gnome]]
:author: Marek Suchánek
:email: marek.suchanek@protonmail.com
:toc:

== Battery Percentage Indicator [[battery-percent]]

To show battery percentage in the top panel, change the `org.gnome.desktop.interface.show-battery-percentage` dconf key:

[source,bash]
----
dconf write \
/org/gnome/desktop/interface/show-battery-percentage \
true
----

== Night Light Temperature [[night-temp]]

To change the Night Light temperature in Gnome 3.24 (newer versions should include a GUI setting), set the `org.gnome.settings-daemon.plugins.color.night-light-temperature` key to your desired temperature. For example, for 4,500 degrees Kelvin:

[source,bash]
----
dconf write \
/org/gnome/settings-daemon/plugins/color/night-light-temperature \
4500
----

== Nautilus Drag-and-Drop Behavior [[nautilus-dnd]]

Nautilus ("Files") opens directories when you hover a dragged item over them. Personally, I don't like this behavior, because it requires me to be quick and precise, which I'm not. Therefore, to disable the automatic folder opening:

[source,bash]
----
dconf write \
/org/gnome/nautilus/preferences/open-folder-on-dnd-hover \
false
----

== Backing Up dconf Settings [[dconf-backup]]

`dconf` settings cannot be copied over to another system or to another user like regular, plain-text files. However, you can export ("dump") them to a text file and then import ("load") them from it again:

[source,bash]
----
dconf dump /path/to/export/ > exported-dconf-settings.txt
dconf load /path/to/import/ < exported-dconf-settings.txt
----

For example:

[source,bash]
----
dconf dump /org/gnome/ > gnome-dconf-settings.txt
dconf load /org/gnome/ < gnome-dconf-settings.txt
----

== Configuring the Compose Key [[compose-key]]

The Compose key allows you to combine a couple of characters on your keyboard to type exotic characters and diacritics. Available combinations are listed in the https://help.ubuntu.com/community/GtkComposeTable[GtkComposeTable] article on the Ubuntu Community Help Wiki.

You can configure your Compose key using the Tweak Tool in the Typing tab. Set it to a key you only rarely use, for example the Menu key or PrintScreen.

To set the Compose key to the Menu, PrintScreen, and Right Win keys (missing keys are ignored), you might also use `dconf`:

[source,bash]
----
dconf write \
/org/gnome/desktop/input-sources/xkb-options \
"['compose:menu', 'compose:prsc', 'compose:rwin']"
----

NOTE: This command rewrites all your Typing preferences you set in the Tweak Tool.

Starting with version 3.20, GTK can read traditional XLib Compose configuration files. You can configure your own composition rules this way, storing them in the `~/.config/gtk-3.0/Compose` or `~/.XCompose` files. For more information, see _Defining custom Compose sequences_ in the http://blog.cyberborean.org/2008/01/06/compose-key-magic[Compose key magic] article on the Cyberborean Chronicles blog.

== Window Switching Shortcuts [[win-switching]]

By default, both the `Alt`-`Tab` and the `Win`-`tab` key (and their `Shift` variants) switch _applications_ in Gnome. This is a matter of taste, but sometimes, you want to simply switch _windows_ instead. A common use case is when an application uses more than one window.

To keep an application-switching shortcut but add a window-switching one as well, configure `Win`-`Tab` to only switch between applications and `Alt`-`Tab` to only switch between windows:

[source,bash]
----
dconf write \
/org/gnome/desktop/wm/keybindings/switch-applications \
"['<Super>Tab']"

dconf write \
/org/gnome/desktop/wm/keybindings/switch-applications-backward \
"['<Shift><Super>Tab']"

dconf write \
/org/gnome/desktop/wm/keybindings/switch-windows \
"['<Alt>Tab']"

dconf write \
/org/gnome/desktop/wm/keybindings/switch-windows-backward \
"['<Shift><Alt>Tab']"
----

As an added bonus, the resulting behavior is consistent with both Windows (window-switching with `Alt`-`Tab`) and Mac (application-switching with `Cmd`-`Tab`).

== Lock Down DConf [[dconf-lockdown]]

Gnome offers ways to https://help.gnome.org/admin/system-admin-guide/stable/user-settings.html.en#lockdown[lock down certain aspects of the user interface]. This is useful when untrusted or unqualified people are expected to use the computer; for example, when setting up an internet kiosk, a public library PC, or when kids are around.

To prevent specific DConf keys from being modified (to lock them down), follow the official Gnome documentation in the https://help.gnome.org/admin/system-admin-guide/stable/dconf-lockdown.html.en[Lock down specific settings] article.

