= Useful packages [[packages]]
include::attributes.adoc[]

== In Fedora [[fedora]]

=== The RPM Fusion repository

To have access to all packages listed on this page, enable the https://rpmfusion.org/[RPM Fusion] _Free_ and _Nonfree_ repositories:

. Install the repository configuration:
+
[source,bash]
----
$ sudo dnf install \
       https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
       https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
----

. Install Appstream metadata packages:
+
[source,bash]
----
$ sudo dnf groupupdate core
----

=== Multimedia [[fedora-multimedia]]

. Install multimedia packages from RPM Fusion:
+
[source,bash]
----
$ sudo dnf groupupdate multimedia \
       --setop="install_weak_deps=False" \
       --exclude=PackageKit-gstreamer-plugin

$ sudo dnf groupupdate sound-and-video
----

. Install other multimedia codecs:
+
[source,bash]
----
$ sudo dnf install \
       ffmpeg-libs \
       gstreamer1-libav \
       gstreamer1-plugin-openh264 \
       gstreamer1-plugins-bad-free \
       gstreamer1-plugins-bad-free-fluidsynth \
       gstreamer1-plugins-bad-freeworld \
       gstreamer1-plugins-ugly \
       pulseaudio-module-bluetooth-freeworld
----

=== Archiving and file systems [[fedora-archiving-fs]]

[source,bash]
----
$ sudo dnf install \
       atool borgbackup exfat-utils f2fs-tools \
       hfsutils lzip lziprecover lzop \
       p7zip p7zip-plugins testdisk udftools unrar
----

=== Various low-level tools [[fedora-various-ll]]

[source,bash]
----
$ sudo dnf install \
       fish htop iftop iotop \
       util-linux-user mc \
       powertop tuned
----

=== Fonts [[fedora-fonts]]

. Install additional fonts:
+
[source,bash]
----
$ sudo dnf install \
       ht-alegreya-\* mozilla-fira\* \
       sil-gentium-fonts sil-gentium-alt-fonts \
       apanov-heuristica-fonts \
       levien-inconsolata-fonts thibault-isabella-fonts lato-fonts \
       linux-libertine\* msimonson-anonymouspro-fonts \
       google-noto-{sans,mono,serif}-fonts \
       google-{arimo,cousine,tinos,carlito}-fonts \
       ht-caladea-fonts \
       oldstandard-sfd-fonts \
       open-sans-fonts overpass-fonts overpass-mono-fonts \
       paratype-pt\* google-roboto\* \
       adobe-source-{code,sans,serif}-pro-fonts \
       gdouros-symbola-fonts impallari-raleway-fonts
----

. Remove the Comfortaa font. It tends to insert itself at inappropriate places, especially in Firefox, and it isn't very readable.
+
[source,bash]
----
$ sudo dnf remove aajohan-comfortaa-fonts
----



== In Debian [[debian]]

To have access to all packages listed here, enable the _Contrib_ and _Non-free_ Debian repositories. This is done by editing the `/etc/apt/sources.list` file.

Here's a sample `sources.list` for Debian Stretch, configured to include all repositories and to download data from the primary Czech server:

----
# Basic repositories
deb http://ftp.cz.debian.org/debian/ stretch main contrib non-free

# Debian Stretch updates
deb http://ftp.cz.debian.org/debian/ stretch-updates main contrib non-free

# Debian Stretch security updates
deb http://security.debian.org/ stretch/updates main contrib non-free

# Debian Stretch backports -- the '-t stretch-backports' option
# has to be specified explicitly to install packages from backports
deb http://ftp.cz.debian.org/debian stretch-backports main contrib non-free
----

Alternatively, you can also use the https://deb.debian.org/[deb.debian.org] service, which automatically determines the fastest server for you each time `apt` downloads data:

----
# Basic repositories
deb http://deb.debian.org/debian/ stretch main contrib non-free

# Debian Stretch updates
deb http://deb.debian.org/debian/ stretch-updates main contrib non-free

# Debian Stretch security updates
deb http://deb.debian.org/debian-security stretch/updates main contrib non-free

# Debian Stretch backports -- the '-t stretch-backports' option
# has to be specified explicitly to install packages from backports
deb http://deb.debian.org/debian stretch-backports main contrib non-free
----

Further references:

- https://wiki.debian.org/SourcesList[A sources.list article on the Debian Wiki]
- https://www.debian.org/mirror/list[Debian mirror list]
- https://debgen.simplylinux.ch/[A sources.list generator]
- https://wiki.debian.org/Backports[Debian backports] – install fresh packages on Debian Stable

=== Multimedia [[debian-multimedia]]

[source,bash]
----
$ apt install \
audacity beets cuetools easytag exfalso flac gimp gnome-backgrounds \
gnome-mpv gnome-music gnome-photos gnome-sound-recorder \
gstreamer1.0-libav gstreamer1.0-packagekit gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-ugly inkscape kde-wallpapers kdeartwork-wallpapers \
kdenlive krita lame libva-drm1 libva-egl1 libva-intel-vaapi-driver \
libva1 libvdpau-va-gl1 libvdpau1 libvulkan1 mcomix mediainfo \
mesa-vdpau-drivers mesa-vulkan-drivers mpv opus-tools quodlibet \
shntool sox vdpauinfo vlc vorbis-tools vulkan-utils youtube-dl \
----

=== Office, Reading and Writing [[debian-read-write]]

[source,bash]
----
$ apt install \
bijiben fbreader gedit-plugins gnome-calendar gnome-dictionary \
gnome-todo gnome-shell-extensions-gpaste libreoffice-style-sifr \
nano neovim pandoc scribus simple-scan vim-nox
----

=== Other Applications [[debian-other-apps]]

[source,bash]
----
$ apt install \
brasero chromium dconf-editor epiphany-browser gnome-builder \
gnome-logs gnome-maps gnome-nettool gnome-packagekit \
gnome-power-manager gnome-tweak-tool tracker-gui transmission-gtk
----

=== Archiving and File Systems [[debian-archiving-fs]]

[source,bash]
----
$ apt install \
atool bleachbit borgbackup exfat-fuse exfat-utils f2fs-tools \
hfsplus hfsutils lzip lziprecover lzop \
p7zip-full progress testdisk udftools unrar xfsdump \
zfs-dkms zfs-initramfs zfsutils-linux 
----

=== Various Low-level Stuff [[debian-various-ll]]

[source,bash]
----
$ apt install \
amd64-microcode beignet-opencl-icd clinfo earlyoom firmware-amd-graphics \
firmware-atheros firmware-brcm80211 firmware-ipw2x00 \
firmware-iwlwifi firmware-linux firmware-linux-free \
firmware-linux-nonfree firmware-misc-nonfree firmware-realtek \
fish htop intel-microcode iftop iotop iucode-tool mc powertop \
sudo tlp zsh
----

=== Czech Localization [[debian-czech-l10n]]

[source,bash]
----
$ apt install \
chromium-l10n firefox-esr-l10n-cs hyphen-cs libreoffice-help-cs \
libreoffice-l10n-cs 
----

=== Fonts [[debian-fonts]]

[source,bash]
----
$ apt install \
fonts-cabin fonts-cabinsketch fonts-cantarell \
fonts-croscore fonts-crosextra-caladea fonts-crosextra-carlito \
fonts-fanwood fonts-firacode fonts-inconsolata fonts-isabella \
fonts-larabie-deco fonts-larabie-uncommon fonts-lato \
fonts-liberation2 fonts-linuxlibertine fonts-hack-otf \
fonts-noto-hinted fonts-noto-mono \
fonts-oldstandard fonts-opendyslexic fonts-open-sans fonts-quattrocento \
fonts-roboto-hinted fonts-sil-gentiumplus fonts-symbola \
ttf-anonymous-pro ttf-essays1743
----

=== Games and Game-related [[debian-games]]

[source,bash]
----
$ apt install \
0ad astromenace blobwars bsdgames crawl crawl-tiles endless-sky fillets-ng \
freecol freeciv frozen-bubble gnome-2048 gnome-games hedgewars \
libtxc-dxtn-s2tc libtxc-dxtn-s2tc-bin lierolibre neverball \
sauerbraten wesnoth
----

== Flatpak [[flatpak]]

- https://flathub.org/apps.html[Flathub]
- https://flatpak.org/apps.html[Flatpak Applications]
