= Useful Packages

== In Fedora

NOTE: Some of these packages require the RPMFusion Free or Non-free repositories enabled.

    \*-backgrounds-extras-gnome atool audacity-freeworld beets beignet \
    bijiben bleachbit brasero bsd-games calligra-krita clinfo \
    cuetools dconf-editor easytag epiphany exfalso exfat-utils f2fs-tools \
    fbreader fish flac freetype-freeworld fuse-exfat gedit-plugins gimp \
    gnome-books gnome-builder gnome-calendar gnome-dictionary gnome-logs \
    gnome-maps gnome-mpv gnome-music gnome-nettool gnome-photos \
    gnome-power-manager gnome-shell-extension-gpaste gnome-sound-recorder \
    gnome-todo gnome-tweak-tool gstreamer1-libav gstreamer1-plugins-bad-free \
    gstreamer1-plugins-bad-free-fluidsynth gstreamer1-plugins-bad-freeworld \
    gstreamer1-plugins-ugly htop chromium inkscape iotop kdenlive lame \
    langpacks-cs libreoffice-langpack-cs libtxc_dxtn libva \
    libva-intel-driver libva-utils libva-vdpau-driver libvdpau lollypop \
    lzip lziprecover lzop mac mc mcomix mediainfo mesa-vdpau-drivers \
    mesa-vulkan-drivers mpv nano opus-tools p7zip p7zip-plugins pandoc \
    powertop quodlibet shntool simple-scan scribus sox testdisk tlp \
    tracker-preferences transmission-gtk tuned unrar vdpauinfo vim vlc \
    vorbis-tools youtube-dl zsh

Pretty *fonts* packaged in Fedora repositories:

    ht-alegreya-\* \*croscore\* \*crosextra\* google-droid-\* mozilla-fira\* \
    sil-gentium-fonts sil-gentium-alt-fonts apanov-heuristica-fonts \
    levien-inconsolata-fonts thibault-isabella-fonts lato-fonts \
    linux-libertine\* google-noto-sans-fonts google-noto-mono-fonts \
    google-noto-serif-fonts google-noto-emoji-fonts oldstandard-sfd-fonts \
    open-sans-fonts paratype-pt\* google-roboto\* cf-sorts-mill-goudy-fonts \
    adobe-source\*fonts gdouros-symbola-fonts

Some free *games*:

    @gnome-games 0ad astromenace blobwars crawl crawl-tiles fillets-ng \
    freecol freecol-manual freeciv frozen-bubble gnome-2048 gnome-hearts \
    hedgewars neverball-neverball openlierox wesnoth

