= Useful Packages [[packages]]
:author: Marek Suchánek
:email: marek.suchanek@protonmail.com
//:source-highlighter: highlightjs
:source-highlighter: prettify
:sectnums:
:toc:

== In Fedora [[fedora]]

// TODO: Add links and instructions about RPMFusion.

NOTE: Some of these packages require the RPMFusion Free or Non-free repositories enabled.

=== Multimedia [[fedora-multimedia]]

[source,bash]
----
\*-backgrounds-extras-gnome audacity-freeworld beets \
cuetools easytag exfalso flac gimp gnome-mpv \
gnome-music gnome-photos gnome-sound-recorder gstreamer1-libav \
gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free-fluidsynth \
gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly inkscape \
kdenlive krita lame libva libva-intel-driver libva-utils \
libva-vdpau-driver libvdpau lollypop mac mcomix mediainfo \
mesa-vdpau-drivers mesa-vulkan-drivers mpv opus-tools quodlibet \
shntool sox vdpauinfo vlc vorbis-tools youtube-dl 
----

=== Archiving and File Systems[[fedora-archiving-fs]]

[source,bash]
----
atool bleachbit exfat-utils f2fs-tools fuse-exfat lzip lziprecover lzop \
p7zip p7zip-plugins unrar testdisk xfsdump 
----

=== Office, Reading and Writing [[fedora-read-write]]

[source,bash]
----
bijiben fbreader gnome-books gnome-calendar gnome-dictionary gedit-plugins \
gnome-shell-extension-gpaste gnome-todo nano pandoc \
simple-scan scribus vim 
----

=== Czech Localization [[fedora-l10n]]

[source,bash]
----
langpacks-cs libreoffice-langpack-cs 
----

=== Other Applications [[fedora-other-apps]]

[source,bash]
----
brasero dconf-editor epiphany gnome-builder gnome-logs gnome-maps \
gnome-nettool gnome-power-manager gnome-tweak-tool chromium \
tracker-preferences transmission-gtk 
----

=== Various Low-level Stuff [[fedora-various-ll]]

[source,bash]
----
beignet clinfo fish freetype-freeworld htop iotop mc powertop tlp tuned zsh
----

=== Fonts [[fedora-fonts]]

[source,bash]
----
ht-alegreya-\* \*croscore\* \*crosextra\* google-droid-\* mozilla-fira\* \
sil-gentium-fonts sil-gentium-alt-fonts apanov-heuristica-fonts \
levien-inconsolata-fonts thibault-isabella-fonts lato-fonts \
linux-libertine\* google-noto-sans-fonts google-noto-mono-fonts \
google-noto-serif-fonts google-noto-emoji-fonts oldstandard-sfd-fonts \
open-sans-fonts paratype-pt\* google-roboto\* cf-sorts-mill-goudy-fonts \
adobe-source\*fonts gdouros-symbola-fonts
----

=== Games and Game-related [[fedora-games]]

[source,bash]
----
@gnome-games 0ad astromenace blobwars bsd-games crawl crawl-tiles \
endless-sky fillets-ng freecol freecol-manual freeciv frozen-bubble \
gnome-2048 gnome-hearts hedgewars libtxc_dxtn neverball-neverball \
openlierox wesnoth
----

=== From Copr [[copr]]

- Neovim: https://copr.fedorainfracloud.org/coprs/dperson/neovim/[dperson/neovim]
- Tilix: https://copr.fedorainfracloud.org/coprs/heikoada/terminix/[heikoada/terminix]

=== From openSUSE Build Service [[obs]]

- "`Vibrancy`" icon theme: https://software.opensuse.org/download.html?project=home%3APival81&package=vibrancy-colors-icon-theme[home:Pival81 / vibrancy-colors-icon-theme]
- "`Moka`" and "`Faba`" icon theme: https://software.opensuse.org/download.html?project=home%3Asnwh%3Amoka&package=moka-icon-theme[home:snwh:moka / moka-icon-theme]
- "`Paper`" icons and GTK theme: https://software.opensuse.org/download.html?project=home%3Asnwh%3Apaper&package=paper-gtk-theme[home:snwh:paper / paper-gtk-theme]

=== From Korora [[korora]]

https://kororaproject.org/[Korora] is an interesting, Fedora-based distribution, which tries to make Fedora as user- and beginner-friendly as possible.

They maintain https://dl.kororaproject.org/pub/korora/releases/[a small add-on repository] for Fedora, where they store their unique packages, not to be found in either Fedora or RPMFusion. Much of this is branding, but some useful packages can be found there, too: for example, `libdvdcss`.

To enable the repository, install the appropriate `korora-release-*.noarch.rpm` package for your Fedora version.

NOTE: Korora versions follow Fedora releases, but are always a few months late.


== In Debian [[debian]]

// TODO: Add a sample sources.list configuration containing everything.

NOTE: Some of these packages may require the Contrib or Nonfree repositories enabled.

=== General Packages [[debian-general]]

[source,bash]
----
amd64-microcode atool audacity beets \
beignet-opencl-icd bijiben bleachbit brasero bsdgames \
chromium chromium-l10n clinfo cuetools dconf-editor \
easytag epiphany-browser exfalso exfat-fuse exfat-utils f2fs-tools \
fbreader firefox-esr-l10n-cs firmware-amd-graphics firmware-atheros \
firmware-brcm80211 firmware-ipw2x00 firmware-iwlwifi firmware-linux \
firmware-linux-free firmware-linux-nonfree firmware-misc-nonfree \
firmware-realtek fish flac gedit-plugins gimp gnome-backgrounds \
gnome-builder gnome-calendar gnome-dictionary gnome-logs gnome-maps \
gnome-mpv gnome-music gnome-nettool gnome-packagekit gnome-photos \
gnome-power-manager gnome-shell-extensions-gpaste gnome-sound-recorder \
gnome-todo gnome-tweak-tool gstreamer1.0-libav gstreamer1.0-packagekit \
gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly htop hyphen-cs \
inkscape intel-microcode iotop iucode-tool \
kde-wallpapers kdeartwork-wallpapers kdenlive krita \
lame libreoffice-help-cs libreoffice-l10n-cs libreoffice-style-sifr \
libtxc-dxtn-s2tc libtxc-dxtn-s2tc-bin libva-drm1 libva-egl1 \
libva-intel-vaapi-driver libva1 libvdpau-va-gl1 libvdpau1 libvulkan1 \
lzip lziprecover lzop mc \
mcomix mediainfo mesa-vdpau-drivers mesa-vulkan-drivers mpv nano neovim \
opus-tools p7zip-full pandoc powertop quodlibet scribus shntool \
simple-scan sox sudo testdisk tlp tracker-gui transmission-gtk unrar \
vdpauinfo vim-nox vlc vorbis-tools vulkan-utils xfsdump youtube-dl \
zfs-dkms zfs-initramfs zfsutils-linux zsh
----

=== Fonts [[debian-fonts]]

[source,bash]
----
fonts-cabin fonts-cabinsketch fonts-cantarell \
fonts-croscore fonts-crosextra-caladea fonts-crosextra-carlito \
fonts-fanwood fonts-inconsolata fonts-isabella \
fonts-larabie-deco fonts-larabie-uncommon fonts-lato \
fonts-liberation2 fonts-linuxlibertine fonts-noto-hinted \
fonts-oldstandard fonts-opendyslexic fonts-quattrocento \
fonts-roboto-hinted fonts-sil-gentiumplus fonts-symbola \
ttf-anonymous-pro ttf-essays1743
----

=== Some Free Games [[debian-games]]

[source,bash]
----
0ad astromenace blobwars crawl crawl-tiles endless-sky fillets-ng \
freecol freeciv frozen-bubble gnome-2048 gnome-games hedgewars \
lierolibre neverball sauerbraten wesnoth
----

