= Useful Packages [[packages]]
:author: Marek Suchánek
:email: marek.suchanek@protonmail.com
//:source-highlighter: highlightjs
:source-highlighter: prettify
:sectnums:
:toc:

== In Fedora [[fedora]]

To have access to all packages listed here, enable the https://rpmfusion.org/[RPM Fusion] _Free_ and _Nonfree_ repositories. Follow their instructions on the https://rpmfusion.org/Configuration[Configuration] page.

Further references:

- https://admin.fedoraproject.org/mirrormanager/[Fedora mirror list]

=== Multimedia [[fedora-multimedia]]

[source,bash]
----
sudo dnf install \
\*-backgrounds-extras-gnome audacity-freeworld beets \
cuetools easytag exfalso flac gimp gnome-mpv \
gnome-music gnome-photos gnome-sound-recorder gstreamer1-libav \
gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free-fluidsynth \
gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly inkscape \
kdenlive krita lame libva libva-intel-driver libva-utils \
libva-vdpau-driver libvdpau lollypop mac mcomix mediainfo \
mesa-vdpau-drivers mesa-vulkan-drivers mpv opus-tools quodlibet \
shntool sox vdpauinfo vlc vorbis-tools youtube-dl 
----

=== Office, Reading and Writing [[fedora-read-write]]

[source,bash]
----
sudo dnf install \
bijiben fbreader gnome-books gnome-calendar gnome-dictionary gedit-plugins \
gnome-shell-extension-gpaste gnome-todo nano neovim pandoc \
simple-scan scribus vim 
----

=== Other Applications [[fedora-other-apps]]

[source,bash]
----
sudo dnf install \
brasero dconf-editor epiphany firewall-config gnome-builder \
gnome-logs gnome-maps \
gnome-nettool gnome-power-manager gnome-tweak-tool chromium \
tilix transmission-gtk 
----

=== Archiving and File Systems[[fedora-archiving-fs]]

[source,bash]
----
sudo dnf install \
atool bleachbit exfat-utils f2fs-tools fuse-exfat lzip lziprecover lzop \
p7zip p7zip-plugins unrar testdisk xfsdump 
----

=== Various Low-level Stuff [[fedora-various-ll]]

[source,bash]
----
sudo dnf install \
beignet clinfo fish freetype-freeworld htop iftop iotop \
util-linux-user mc \
powertop tlp tuned zsh
----

=== Czech Localization [[fedora-czech-l10n]]

[source,bash]
----
sudo dnf install \
langpacks-cs libreoffice-langpack-cs 
----

=== Fonts [[fedora-fonts]]

[source,bash]
----
sudo dnf install \
ht-alegreya-\* \*croscore\* \*crosextra\* google-droid-\* mozilla-fira\* \
sil-gentium-fonts sil-gentium-alt-fonts apanov-heuristica-fonts \
levien-inconsolata-fonts thibault-isabella-fonts lato-fonts \
linux-libertine\* msimonson-anonymouspro-fonts \
google-noto-sans-fonts google-noto-mono-fonts \
google-noto-serif-fonts google-noto-emoji-fonts oldstandard-sfd-fonts \
open-sans-fonts overpass-fonts overpass-mono-fonts \
paratype-pt\* google-roboto\* cf-sorts-mill-goudy-fonts \
adobe-source\*fonts gdouros-symbola-fonts impallari-raleway-fonts
----

=== Games and Game-related [[fedora-games]]

[source,bash]
----
sudo dnf install \
@gnome-games 0ad astromenace blobwars bsd-games crawl crawl-tiles \
endless-sky fillets-ng freecol freecol-manual freeciv frozen-bubble \
gnome-2048 gnome-hearts hedgewars libtxc_dxtn neverball-neverball \
openlierox wesnoth
----

=== From Copr [[fedora-copr]]

- Hack fonts: https://copr.fedorainfracloud.org/coprs/heliocastro/hack-fonts/[heliocastro/hack-fonts]

=== From openSUSE Build Service [[obs]]

- "`Vibrancy`" icon theme: https://software.opensuse.org/download.html?project=home%3APival81&package=vibrancy-colors-icon-theme[home:Pival81 / vibrancy-colors-icon-theme]
- "`Moka`" and "`Faba`" icon theme: https://software.opensuse.org/download.html?project=home%3Asnwh%3Amoka&package=moka-icon-theme[home:snwh:moka / moka-icon-theme]
- "`Paper`" icons and GTK theme: https://software.opensuse.org/download.html?project=home%3Asnwh%3Apaper&package=paper-gtk-theme[home:snwh:paper / paper-gtk-theme]

=== From Korora [[korora]]

https://kororaproject.org/[Korora] is an interesting, Fedora-based distribution, which tries to make Fedora as user- and beginner-friendly as possible.

They maintain https://dl.kororaproject.org/pub/korora/releases/[a small add-on repository] for Fedora, where they store their unique packages, not to be found in either Fedora or RPMFusion. Much of this is branding, but some useful packages can be found there, too: for example, `libdvdcss`.

To enable the repository, install the appropriate `korora-release-*.noarch.rpm` package for your Fedora version.

NOTE: Korora versions follow Fedora releases, but are always a few months late.


== In Debian [[debian]]

To have access to all packages listed here, enable the _Contrib_ and _Non-free_ Debian repositories. This is done by editing the `/etc/apt/sources.list` file.

Here's a sample `sources.list` for Debian Stretch, configured to include all repositories and to download data from the primary Czech server:

----
# Basic repositories
deb http://ftp.cz.debian.org/debian/ stretch main contrib non-free

# Debian Stretch updates
deb http://ftp.cz.debian.org/debian/ stretch-updates main contrib non-free

# Debian Stretch security updates
deb http://security.debian.org/ stretch/updates main contrib non-free

# Debian Stretch backports -- the '-t stretch-backports' option
# has to be specified explicitly to install packages from backports
deb http://ftp.cz.debian.org/debian stretch-backports main contrib non-free
----

Alternatively, you can also use the https://deb.debian.org/[deb.debian.org] service, which automatically determines the fastest server for you each time `apt` downloads data:

----
# Basic repositories
deb http://deb.debian.org/debian/ stretch main contrib non-free

# Debian Stretch updates
deb http://deb.debian.org/debian/ stretch-updates main contrib non-free

# Debian Stretch security updates
deb http://deb.debian.org/debian-security stretch/updates main contrib non-free

# Debian Stretch backports -- the '-t stretch-backports' option
# has to be specified explicitly to install packages from backports
deb http://deb.debian.org/debian stretch-backports main contrib non-free
----

Further references:

- https://wiki.debian.org/SourcesList[A sources.list article on the Debian Wiki]
- https://www.debian.org/mirror/list[Debian mirror list]
- https://debgen.simplylinux.ch/[A sources.list generator]
- https://wiki.debian.org/Backports[Debian backports] – install fresh packages on Debian Stable

=== Multimedia [[debian-multimedia]]

[source,bash]
----
apt install \
audacity beets cuetools easytag exfalso flac gimp gnome-backgrounds \
gnome-mpv gnome-music gnome-photos gnome-sound-recorder \
gstreamer1.0-libav gstreamer1.0-packagekit gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-ugly inkscape kde-wallpapers kdeartwork-wallpapers \
kdenlive krita lame libva-drm1 libva-egl1 libva-intel-vaapi-driver \
libva1 libvdpau-va-gl1 libvdpau1 libvulkan1 mcomix mediainfo \
mesa-vdpau-drivers mesa-vulkan-drivers mpv opus-tools quodlibet \
shntool sox vdpauinfo vlc vorbis-tools vulkan-utils youtube-dl \
----

=== Office, Reading and Writing [[debian-read-write]]

[source,bash]
----
apt install \
bijiben fbreader gedit-plugins gnome-calendar gnome-dictionary \
gnome-todo gnome-shell-extensions-gpaste libreoffice-style-sifr \
nano neovim pandoc scribus simple-scan vim-nox
----

=== Other Applications [[debian-other-apps]]

[source,bash]
----
apt install \
brasero chromium dconf-editor epiphany-browser gnome-builder \
gnome-logs gnome-maps gnome-nettool gnome-packagekit \
gnome-power-manager gnome-tweak-tool tracker-gui transmission-gtk
----

=== Archiving and File Systems [[debian-archiving-fs]]

[source,bash]
----
apt install \
atool bleachbit exfat-fuse exfat-utils f2fs-tools lzip lziprecover lzop \
p7zip-full testdisk unrar xfsdump zfs-dkms zfs-initramfs zfsutils-linux 
----

=== Various Low-level Stuff [[debian-various-ll]]

[source,bash]
----
apt install \
amd64-microcode beignet-opencl-icd clinfo firmware-amd-graphics \
firmware-atheros firmware-brcm80211 firmware-ipw2x00 \
firmware-iwlwifi firmware-linux firmware-linux-free \
firmware-linux-nonfree firmware-misc-nonfree firmware-realtek \
fish htop intel-microcode iftop iotop iucode-tool mc powertop \
sudo tlp zsh
----

=== Czech Localization [[debian-czech-l10n]]

[source,bash]
----
apt install \
chromium-l10n firefox-esr-l10n-cs hyphen-cs libreoffice-help-cs \
libreoffice-l10n-cs 
----

=== Fonts [[debian-fonts]]

[source,bash]
----
apt install \
fonts-cabin fonts-cabinsketch fonts-cantarell \
fonts-croscore fonts-crosextra-caladea fonts-crosextra-carlito \
fonts-fanwood fonts-firacode fonts-inconsolata fonts-isabella \
fonts-larabie-deco fonts-larabie-uncommon fonts-lato \
fonts-liberation2 fonts-linuxlibertine fonts-hack-otf \
fonts-noto-hinted fonts-noto-mono \
fonts-oldstandard fonts-opendyslexic fonts-open-sans fonts-quattrocento \
fonts-roboto-hinted fonts-sil-gentiumplus fonts-symbola \
ttf-anonymous-pro ttf-essays1743
----

=== Games and Game-related [[debian-games]]

[source,bash]
----
apt install \
0ad astromenace blobwars bsdgames crawl crawl-tiles endless-sky fillets-ng \
freecol freeciv frozen-bubble gnome-2048 gnome-games hedgewars \
libtxc-dxtn-s2tc libtxc-dxtn-s2tc-bin lierolibre neverball \
sauerbraten wesnoth
----

== Flatpak [[flatpak]]

- https://flathub.org/apps.html[Flathub]
- http://flatpak.org/apps.html[Flatpak Applications]

