= Useful Packages

== In Fedora

NOTE: Some of these packages require the RPMFusion Free or Non-free repositories enabled.

=== General Packages

    \*-backgrounds-extras-gnome atool audacity-freeworld beets beignet \
    bijiben bleachbit brasero bsd-games clinfo \
    cuetools dconf-editor easytag epiphany exfalso exfat-utils f2fs-tools \
    fbreader fish flac freetype-freeworld fuse-exfat gedit-plugins gimp \
    gnome-books gnome-builder gnome-calendar gnome-dictionary gnome-logs \
    gnome-maps gnome-mpv gnome-music gnome-nettool gnome-photos \
    gnome-power-manager gnome-shell-extension-gpaste gnome-sound-recorder \
    gnome-todo gnome-tweak-tool gstreamer1-libav gstreamer1-plugins-bad-free \
    gstreamer1-plugins-bad-free-fluidsynth gstreamer1-plugins-bad-freeworld \
    gstreamer1-plugins-ugly htop chromium inkscape iotop kdenlive krita lame \
    langpacks-cs libreoffice-langpack-cs libtxc_dxtn libva \
    libva-intel-driver libva-utils libva-vdpau-driver libvdpau lollypop \
    lzip lziprecover lzop mac mc mcomix mediainfo mesa-vdpau-drivers \
    mesa-vulkan-drivers mpv nano opus-tools p7zip p7zip-plugins pandoc \
    powertop quodlibet shntool simple-scan scribus sox testdisk tlp \
    tracker-preferences transmission-gtk tuned unrar vdpauinfo vim vlc \
    vorbis-tools youtube-dl zsh

=== Fonts

    ht-alegreya-\* \*croscore\* \*crosextra\* google-droid-\* mozilla-fira\* \
    sil-gentium-fonts sil-gentium-alt-fonts apanov-heuristica-fonts \
    levien-inconsolata-fonts thibault-isabella-fonts lato-fonts \
    linux-libertine\* google-noto-sans-fonts google-noto-mono-fonts \
    google-noto-serif-fonts google-noto-emoji-fonts oldstandard-sfd-fonts \
    open-sans-fonts paratype-pt\* google-roboto\* cf-sorts-mill-goudy-fonts \
    adobe-source\*fonts gdouros-symbola-fonts

=== Some Free Games

    @gnome-games 0ad astromenace blobwars crawl crawl-tiles endless-sky \
    fillets-ng freecol freecol-manual freeciv frozen-bubble gnome-2048 \
    gnome-hearts hedgewars neverball-neverball openlierox wesnoth

=== From Copr

- Neovim: `dperson/neovim`
- Tilix: `heikoada/terminix`
- SyncThing: `tune2fs/syncthing`


== In Debian

NOTE: Some of these packages may require the Contrib or Nonfree repositories enabled.

=== General Packages

    atool audacity beets beignet-opencl-icd bijiben bleachbit brasero \
    bsdgames chromium chromium-l10n clinfo cuetools dconf-editor easytag \
    epiphany-browser exfalso exfat-fuse exfat-utils f2fs-tools fbreader \
    firefox-esr-l10n-cs fish flac gedit-plugins gimp gnome-backgrounds \
    gnome-builder gnome-calendar gnome-dictionary gnome-logs gnome-maps \
    gnome-mpv gnome-music gnome-nettool gnome-packagekit gnome-photos \
    gnome-power-manager gnome-shell-extensions-gpaste gnome-sound-recorder \
    gnome-todo gnome-tweak-tool gstreamer1.0-libav gstreamer1.0-packagekit \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly htop hyphen-cs \
    inkscape iotop kde-wallpapers kdenlive krita lame libreoffice-help-cs \
    libreoffice-l10n-cs libreoffice-style-sifr libtxc-dxtn-s2tc \
    libtxc-dxtn-s2tc-bin libva-drm1 libva-egl1 libva-intel-vaapi-driver \
    libva1 libvdpau-va-gl1 libvdpau1 libvulkan1 lzip lziprecover lzop mc \
    mcomix mediainfo mesa-vdpau-drivers mesa-vulkan-drivers mpv nano neovim \
    opus-tools p7zip-full pandoc powertop quodlibet scribus shntool \
    simple-scan sox testdisk tlp tracker-gui transmission-gtk unrar \
    vdpauinfo vim-nox vlc vorbis-tools vulkan-utils youtube-dl \
    zfs-dkms zfs-initramfs zfsutils-linux zsh

=== Fonts

TODO

    fonts-symbola

=== Some Free Games

    0ad astromenace blobwars crawl crawl-tiles endless-sky fillets-ng \
    freecol freeciv frozen-bubble gnome-2048 gnome-games hedgewars \
    lierolibre neverball sauerbraten wesnoth

