= System Tuning [[system-tuning]]

== Common Options [[common-options]]

== XFS [[xfs]]

XFS is the default file system in Red Hat Enterprise Linux. It requires no tuning per se, but there are useful tools for it and things to consider when using XFS.

XFS is great for:

- large files
- large partitions
- parallel access to many files

Also, its kernel code is said to be very clean and maintainable, compared to ext4.

The CFQ disk scheduler, which is currently the default, enforces single-threaded access to the disk and, consequently, prevents XFS from utilizing its parallelism fully. To enjoy your parallelism, switch to a different scheduler: for example, deadline, or Kyber when using blk-mq. (For blk-mq, see <<blk-mq>>.) However, you should only do this on an SSD or another fast disk. HDDs perform best when access is single-threaded.

Some XFS-related tools:

- To get information about an XFS partition: `xfs_info`
- To back-up a file system: `xfsdump`
- To recover from back up: `xsfrestore`
- To repair an XFS file system: `xfs_repair`
- To calculate the fragmentation of a file system: `xfs_db -c frag -r <partition>`
- To defragment a file system: `xfs_fsr <partition>`

Red Hat documentation: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch-xfs.html[XFS in the Storage Administration Guide]

=== zswap [[zswap]]

`zswap` is a kernel feature, which compresses data in RAM that would otherwise need to be written to the swap partition. In effect, it increases the amount of data that can be stored in RAM, lowers swap partition usage, and increases overall system performance, especially when using a slow disk and little RAM.

It can be enabled using this kernel parameter in /etc/default/grub:

    zswap.enabled=1

The current state of `zswap` can be read from the /sys/module/zswap/parameters/enabled file: 0 for off, 1 for on.

Run-time `zswap` statistics are recorded in the /sys/kernel/debug/zswap file.

=== journald [[journald]]

The current disk usage of `journalctl` can be displayed using the following command:

    sudo journalctl --disk-usage

`journald` configuration is located in the /etc/systemd/journald.conf file. It's probably a good idea to explicitly limit how much data `journald` can store. In the configuration file, set something like:

    SystemMaxUse=256M
    RuntimeMaxUse=128M

=== Block Device Multi Queue [[blk-mq]]

The multiqueue block layer can be enabled by setting the `scsi_mod.use_blk_mq=1` kernel parameter in /etc/default/grub.

The current value is available in the /sys/module/scsi_mod/parameters/use_blk_mq file.

The blk-mq has its own set of disk schedulers, which are multiqueue-capable. They can no longer be set using the `elevator` kernel parameter. They are configured by setting udev rules instead.

To configure blk-mq disk schedulers, create a /etc/udev/rules.d/60-scheduler.rules file containing something like this:

    ## Set the BFQ scheduler for all disks:
    # ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="bfq"
    ## Set the BFQ scheduler for all rotational disks:
    ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1",           
    ATTR{queue/scheduler}="bfq"
    ## Set the Kyber scheduler for all non-rotational disks:
    ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0",           
    ATTR{queue/scheduler}="kyber"

If your kernel has been compiled with BFQ and Kyber set as modules, you also need to create the /etc/modules-load.d/schedulers.conf file. In it, put the module names to be loaded:

    bfq
    kyber-iosched

NOTE: The way the kernel detects rotational vs. non-rotational devices isn't very reliable. It falls back on rotational. All my flash drives have been detected as rotational for some reason. Therefore, configure the schedulers more explicitly if you want consistent behavior.

=== Memory Tuning for Interactive Use [[memory-tuning]]

https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[Certain people] argue that the way Linux handles interactive desktop usage leaves much to be desired. They also suggest ways to improve that.

In the /etc/sysctl.conf file, set:

    vm.swappiness=10
    vm.vfs_cache_pressure=50

Or, if you want to be more conservative, set:

    vm.swappiness=20
    vm.vfs_cache_pressure=80

In comparison, the default values are:

    vm.swappiness=60
    vm.vfs_cache_pressure=100

However, note that there is little "scientific" proof that modifying these actually helps. Experiment if you need to be sure. Rodd-O https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[devises a way to test the impact] in their article mentioned earlier.

=== Gnome [[gnome]]

To show battery percentage in the top panel, change the `org.gnome.desktop.interface.show-battery-percentage` dconf key:

    dconf write /org/gnome/desktop/interface/show-battery-percentage true

To change the Night Light temperature in Gnome 3.24 (newer versions should include a GUI setting), set the `org.gnome.settings-daemon.plugins.color.night-light-temperature` key to your desired temperature. For example, for 4,500 degrees Kelvin:

    dconf write /org/gnome/settings-daemon/plugins/color/night-light-temperature 4500

Nautilus ("Files") opens directories when you hover a dragged item over them. Personally, I don't like this behavior, because it requires me to be quick and precise, which I'm not. Therefore, to disable the automatic folder opening:

    dconf write /org/gnome/nautilus/preferences/open-folder-on-dnd-hover false

`dconf` settings cannot be copied over to another system or to another user like regular, plain-text files. However, you can export ("dump") them to a text file and then import ("load") them from it again:

    dconf dump /path/to/export/ > exported-dconf-settings.txt
    dconf load /path/to/import/ < exported-dconf-settings.txt

For example:

    dconf dump /org/gnome/ > gnome-dconf-settings.txt
    dconf load /org/gnome/ < gnome-dconf-settings.txt

== Fedora-Specific Options [[fedora-specific]]

TODO

== Debian-Specific Options [[debian-specific]]

TODO

