= System Tuning [[system-tuning]]
:author: Marek Suchánek
:email: marek.suchanek@protonmail.com
//:source-highlighter: highlightjs
:source-highlighter: prettify
:sectnums:
:toc:

== Common Options [[common-options]]

=== XFS [[xfs]]

XFS is the default file system in Red Hat Enterprise Linux. It requires no tuning per se, but there are useful tools for it and things to consider when using XFS.

XFS is great for:

- large files
- large partitions
- parallel access to many files

Also, its kernel code is said to be very clean and maintainable, compared to ext4.

The CFQ disk scheduler, which is currently the default, enforces single-threaded access to the disk and, consequently, prevents XFS from utilizing its parallelism fully. To enjoy your parallelism, switch to a different scheduler: for example, deadline, or Kyber when using blk-mq. (For blk-mq, see <<blk-mq>>.) However, you should only do this on an SSD or another fast disk. HDDs perform best when access is single-threaded.

Some XFS-related tools:

- To get information about an XFS partition: `xfs_info`
- To back up a file system: `xfsdump`
- To recover from backup: `xsfrestore`
- To repair an XFS file system: `xfs_repair`
- To calculate the fragmentation of a file system: `xfs_db -c frag -r <partition>`
- To defragment a file system: `xfs_fsr <partition>`

Red Hat documentation: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch-xfs.html[XFS in the Storage Administration Guide]

=== zswap [[zswap]]

`zswap` is a kernel feature, which compresses data in RAM that would otherwise need to be written to the swap partition. In effect, it increases the amount of data that can be stored in RAM, lowers swap partition usage, and increases overall system performance, especially when using a slow disk and little RAM.

It can be enabled using this kernel parameter in `/etc/default/grub`:

----
zswap.enabled=1
----

After that, update `grub2` configuration as described in <<update-grub>> and reboot.

The current state of `zswap` can be read from the `/sys/module/zswap/parameters/enabled` file: 0 for off, 1 for on.

Run-time `zswap` statistics are recorded in the `/sys/kernel/debug/zswap` file.

=== journald Disk Usage [[journald-disk-usage]]

The current disk usage of `journalctl` can be displayed using the following command:

[source,bash]
----
sudo journalctl --disk-usage
----

`journald` configuration is located in the `/etc/systemd/journald.conf` file. It's probably a good idea to explicitly limit how much data `journald` can store. In the configuration file, set something like:

----
SystemMaxUse=256M
RuntimeMaxUse=128M
----

=== System Logging in a Console [[console-log]]

You can configure your system log service to print log entries in a system console: for example, TTY10. In case of `journald`, this boils down to adding the following lines to the `/etc/systemd/journald.conf` configuration file:

[subs=+quotes]
----
ForwardToConsole=yes
TTYPath=/dev/tty__N__
----

Replace `__N__` with the number of the console of your choosing. Note that Fedora assigns graphical user interfaces to `tty1` and subsequent consoles, while more traditional distributions like Debian start from `tty7`.

Afterwards, restart the `journald` service:

[source,bash]
----
sudo systemctl restart systemd-journald
----

=== Block Device Multi Queue [[blk-mq]]

The multiqueue block layer can be enabled by setting the `scsi_mod.use_blk_mq=1` kernel parameter in `/etc/default/grub`.

The current value is available in the `/sys/module/scsi_mod/parameters/use_blk_mq` file.

The blk-mq has its own set of disk schedulers, which are multiqueue-capable. They can no longer be set using the `elevator` kernel parameter. They are configured by setting udev rules instead.

To configure blk-mq disk schedulers, create a `/etc/udev/rules.d/60-scheduler.rules` file containing something like this:

----
## Set the BFQ scheduler for all disks:
# ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="bfq"

## Set the BFQ scheduler for all rotational disks:
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"

## Set the Kyber scheduler for all non-rotational disks:
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="kyber"
----

If your kernel has been compiled with BFQ and Kyber set as modules, you also need to create the `/etc/modules-load.d/schedulers.conf` file. In it, put the module names to be loaded:

----
bfq
kyber-iosched
----

NOTE: The way the kernel detects rotational vs. non-rotational devices isn't very reliable. It falls back on rotational. All my flash drives have been detected as rotational for some reason. Therefore, configure the schedulers more explicitly if you want consistent behavior.

=== Memory Tuning for Interactive Use [[memory-tuning]]

https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[Certain people] argue that the way Linux handles interactive desktop usage leaves much to be desired. They also suggest ways to improve that.

In the `/etc/sysctl.conf` file, set:

----
vm.swappiness=10
vm.vfs_cache_pressure=50
----

Or, if you want to be more conservative, set:

----
vm.swappiness=20
vm.vfs_cache_pressure=80
----

In comparison, the default values are:

----
vm.swappiness=60
vm.vfs_cache_pressure=100
----

However, note that there is little "scientific" proof that modifying these actually helps. Experiment if you need to be sure. Rodd-O https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[devises a way to test the impact] in their article mentioned earlier.

Afterwards, update the initial ramdisk; see <<rebuild-initramfs>>.

=== Early OOM Killer [[early-oom]]

The Linux "out-of-memory killer" (OOM Killer) is supposed to terminate the process that uses the most memory when the system is running out of RAM. However, it hardly ever actually executes: it is overly optimistic that the system can eventually handle the problem on its own. This leads to situations when the memory is hopelessly full while the system stays unresponsive for hours until the user presses the power button.

Therefore, an alternative, user-space implementation has been created, `earlyoom`, which is much more strict and predictable.

The `earlyoom` service runs in the background and checks for memory conditions. By default, it kills a process when both the RAM and the swap partition are at least 90% full. These values are configurable.

For details on installation and usage, see the GitHub page: https://github.com/rfjakob/earlyoom[rfjakob/earlyoom]. The context was also discussed on Reddit: https://www.reddit.com/r/linux/comments/7e0pgm/earlyoom_early_oom_daemon/[earlyoom - Early OOM daemon].

The `earlyoom` service is packaged both for Fedora and Debian.


.oomd

There's also an alternative service written by Facebook: link:https://github.com/facebookincubator/oomd[]. According to the readme, it's more flexible, allowing arbitrary code to be executed in low-memory situations.

=== Update grub2 Configuration [[update-grub]]

After editing the `/etc/default/grub` file, the configuration has to be compiled for `grub2` to be able to use it:

- On Debian, all you have to do is type:
+
[source,bash]
----
sudo update-grub2
----
+
- On Fedora, follow these steps:
. Locate the compiled configuration file:
+
[source,bash]
----
sudo find /boot -name grub.cfg
----
+
. Copy the file name the previous command gave you and use it here:
+
[source,bash,subs=+quotes]
....
sudo grub2-mkconfig -o /boot/__path/to/__grub.cfg
....

=== Setting Up the "Magic SysRq Keys" [[magic-sysrq]]

"Magic SysRq Keys" are keyboard shortcuts that are registered at the kernel level and allow you to control the basic functions of system even if it has otherwise completely frozen.

A common use case is to shut down the frozen system safely by typing `Alt`-`SysRq`-`s` to write (sync) all disk buffers, followed by `Alt`-`SysRq`-`u` to remount all disks read-only, and `Alt`-`SysRq`-`b` to reboot the system immediately.

Many more shortcuts are listed in the https://en.wikipedia.org/wiki/Magic_SysRq_key#Commands[Magic SysRq key] article on Wikipedia.

To set up Magic SysRq, open the `/etc/sysctl.conf` file as root and add:

----
kernel.sysrq = 1
----

Afterwards, update the initial ramdisk; see <<rebuild-initramfs>>.

=== Synchronized Time Zones when Dual-booting with Windows [[dual-boot-time-zones]]

Linux sets the hardware clock to the current time in UTC, while Windows sets it to the local time. This conflict results the clock being off a few hours when switching operating systems.

One solution is to persuade Linux to use local time instead. Surprisingly, this is extremely hard, as core system services expect UTC.

The other way is to configure Windows to use UTC. This is relatively easy. The Arch Linux Wiki describes the process in the https://wiki.archlinux.org/index.php/Time#UTC_in_Windows[UTC in Windows] section of the https://wiki.archlinux.org/index.php/Time[Time] article.

=== Disable watchdog

`watchdog` is a kernel service, which allows to debug system lock-ups. However, to be honest, it's really not that useful for you as a desktop user. On the other hand, it periodically creates interrupts, which wake the CPU up from low-power sleep. Therefore, if power consumption is a concern, you can safely turn `watchdog` off.

There are two main ways to configure `watchdog`: in a kernel parameter or using `sysctl`. They should have the same effect, so it's up to you which one to choose.

- To disable `watchdog` using a kernel parameter:
. Edit the `/etc/default/grub` file and add the following to the kernel command line:
+
----
nmi_watchdog=0
----
+
. Update `grub2` configuration as described in <<update-grub>>.
- To disable `watchdog` using `sysctl`, edit the `/etc/sysctl.conf` and add there:
+
----
kernel.nmi_watchdog=0
----

You can read the current state of `watchdog` from the `/proc/sys/kernel/nmi_watchdog` file: `0` for disabled, `1` for enabled`.

Afterwards, update the initial ramdisk; see <<rebuild-initramfs>>.

=== Trimming Your SSD [[fstrim]]

If your computer uses a solid-state disk (SSD), you should https://en.wikipedia.org/wiki/Trim_(computing)["trim"] the file systems on it regularly. Your distributions might already do that for you: Ubuntu runs `fstrim` weekly.

On Fedora and Debian, you need to manually enable a service that trims disks periodically:

. If you're using Debian, copy the service file so that it can be actually used:
+
[source,bash]
----
sudo cp /usr/share/doc/util-linux/examples/fstrim.{service,timer} \
        -t /etc/systemd/system/
----

. Enable the weekly timer:
+
[source,bash]
----
sudo systemctl enable fstrim.timer
----

=== Configuring the Virtual Console [[console-font]]

The Linux virtual console, which displays, for example, the boot process, uses its own font and keyboard layout settings. These can be modified either on the kernel command line or in the `/etc/vconsole.conf` configuration file.

By default, Fedora uses the classic _eurlatgr_ font, while Debian has switched to the great, but much more opinionated, _Terminus_ font. To see the console fonts available on your system, browse the `/lib/kbd/consolefonts/` directory. To install _Terminus_ on Fedora, use:

[source,bash]
----
sudo dnf install terminus-fonts-console
----

Then, edit the `/etc/vconsole.conf` file and set the `FONT` variable. For example, for the console to use _Terminus_ size 18 for Central European encodings:

----
FONT="ter-218n"
----

This can also be achieved by adding the `vconsole.font=ter-218n` parameter to the kernel command line in the `/etc/default/grub` file.

// TODO: Find out whether there's any benefit in using the kernel option.

See also the *vconsole.conf*(5) man page for more information on configuring the console, including the keyboard layout.

=== Rebuilding the Initial Ramdisk [[rebuild-initramfs]]

After changing `sysctl` settings, rebuilt the initial ramdisk in order for the updated settings to take effect early in the boot process.

- In Fedora:
+
[source,bash]
----
sudo dracut -f
----

- In Debian:
+
[source,bash]
----
sudo update-initramfs
----
+
Or:
+
[source,bash]
----
sudo dracut-update-initramfs
----

=== Updating Firmware

Some manufacturers (mostly Dell, Lenovo) provide firmware updates via the native Linux `fwupd` mechanism.

* To check for updates:
+
----
sudo fwupdmgr refresh
sudo fwupdmgr get-updates
----

* To apply them:
+
----
sudo fwupdmgr update
----

=== A Tuned Profile to Increase Desktop Responsiveness [[tuned-responsiveness]]

. Install and enable the `tuned` service.

. Create the `/etc/tuned/interactive/tuned.conf` file with the following content:
+
----
[main]
summary=My own Tuned profile for an interactive desktop system
include=desktop

[cpu]
governor=ondemand|powersave

[sysctl]
# The defaults on Fedora 30; these values are interdependent:
# kernel.sched_min_granularity_ns=2250000   
# kernel.sched_latency_ns=18000000
# kernel.sched_wakeup_granularity_ns=3000000  

# The defaults divided by 4 to reduce latency:
kernel.sched_min_granularity_ns=562500   
kernel.sched_latency_ns=4500000
kernel.sched_wakeup_granularity_ns=750000

vm.swappiness=10
vm.vfs_cache_pressure=50

[disk]
# On all disks, use BFQ, which is an excellent scheduler for interactivity
elevator=bfq

[sysfs]
# Apply some tunings to sda, which should be the primary and also the fastest disk on your system (at least on desktops and laptops)

# Low latency in mq-deadline in case it's set instead of BFQ:
# /sys/block/sda/queue/iosched/fifo_batch=8
# /sys/block/sda/queue/iosched/read_expire=50

# Low latency in BFQ (optional because BFQ already works well on its own):
# Halve the idle wait time; should improve throughput on SSDs
/sys/block/sda/queue/iosched/slice_idle=4
# Halve the time to expire read requests
/sys/block/sda/queue/iosched/fifo_expire_sync=62
/sys/block/sda/queue/iosched/timeout_sync=62

# Power-saving features
[audio]
timeout=10
----

. Apply the profile:
+
----
sudo tuned-adm profile interactive
----


=== Improving Audio Quality [[audio-quality]]

There's been an excellent discussion on Reddit about the audio stack on Linux: link:https://www.reddit.com/r/linux/comments/coi4dt/a_complete_guide_of_and_debunking_of_audio_on/[A complete guide of and debunking of audio on Linux, ALSA and Pulse].

The easiest and most obvious option to improve sound quality is to set a better resampling algorithm using the `resample-method` option in the `/etc/pulse/daemon.conf` file. Consider:

* `speex-float-3` as recommended by the developers of Speex: link:https://www.speex.org/docs/manual/speex-manual/node7.html#SECTION00760000000000000000[]
* `speex-float-5` as suggested by freedesktop.org: link:https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Audiophile/[]


=== My Personal Dotfiles [[my-dotfiles]]

Many people keep their config files in a git repository, myself included. If you'd like to use my _dotfiles_ or just get some inspiration, see my https://gitlab.com/mrksu/dotfiles[dotfiles] repository on GitLab.

=== Guides to Set Up Dotfiles [[dotfiles-guides]]

* link:https://dotfiles.github.io/[]
* link:https://www.gnu.org/software/stow/[]
* link:https://medium.com/@webprolific/getting-started-with-dotfiles-43c3602fd789[]

=== Password Management [[passwords]]

* link:https://bitwarden.com/[]


== Fedora-Specific Options [[fedora-specific]]

=== Remove Unnecessary Services [[fedora-unnecessary-services]]

Until this gets fixed:

link:https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/UFGNO5MTPCLEK5B5RCJGGZUFTZ7JTWI5/[]

=== Enable Automatic Updates in Fedora [[fedora-auto-update]]

Fedora can automatically install package updates at configurable times using the `dnf-automatic` package and the `dnf-automatic-download.timer` or `dnf-automatic-install.timer` systemd units.

For more information, see the https://www.ctrl.blog/entry/how-to-dnf-automatic[How to get Fedora to take care of its own updates] article on the _Ctrl blog_.

=== Limit coredump Disk Usage [[limit-coredump]]

`coredump` is a mechanism that Fedora uses to analyze application crashes and send automated bug reports. The application's memory space is saved to a file on your disk. These files can easily be gigabytes in size, and while the default configuration places some limits on their total size, we can be more strict.

To limit `coredump` to use 2 gigabytes of disk space at most, open the `/etc/systemd/coredump.conf` and add:

----
MaxUse=2G
----

=== The Number of Kernels Kept Installed

Fedora keeps only a certain number of kernel versions installed in parallel. When a new version is being installed, the oldest one is deleted automatically is the limit has been exceeded. The default number is 3.

To change the number of installable kernel versions, open the `/etc/dnf/dnf.conf` and edit the `installonly_limit=3` line.

=== Restrict or Disable SELinux

Fedora utilizes SELinux, a kernel mechanism that watches which processes access which files and only allows those access patterns which have been allowed in SELinux rules.

This is great for security, at least in theory, but might cause trouble if you're doing something for what nobody has written SELinux rules. For example, SELinux might deny some power-tweaking programs from taking effect because it deems them suspicious.

If you see SELinux warnings on your desktop, there are three ways to deal with them for good:

- File bugs, create new SELinux rules. `aintnobodygottimefothat.gif`
- Configure SELinux to still show warnings but allow all access. The "permissive" mode.
- Disable SELinux altogether.

Configuration can be changed in the `/etc/selinux/config` file, on the `SELINUX=` line. The default is `SELINUX=enforcing`, and you can change it to:

- `SELINUX=permissive` for the permissive mode
- `SELINUX=disabled` to disable SELinux

== Debian-Specific Options [[debian-specific]]

=== Configuring sudo [[sudo-config]]

. Become root the traditional way:
+
[source,bash]
----
su
----

. Install the `sudo` package. This is already included in the <<packages#packages,Useful Packages>> chapter, but anyway, to make sure:
+
[source,bash]
----
apt install sudo
----

. Add your user to the group `sudo`:
+
[source,bash,subs=+quotes]
....
usermod -a -G sudo __your_user_name__
....

. Reboot your system.

=== Enable Automatic Updates in Debian [[debian-auto-update]]

Debian can automatically install package updates at configurable times using the Unattended Upgrades feature.

For more information, see the https://wiki.debian.org/UnattendedUpgrades[UnattendedUpgrades] page on the Debian Wiki.

=== journald as the Only Log [[only-journald]]

By default, Debian uses `rsyslog` as the system log service. However, `journald` is running anyway all the time and there's no reason to have two log service, other than that `rsyslog` provides plain-text logs. If that doesn't sound compelling to you:

- Disable `rsyslog`:
+
[source,bash]
----
sudo systemctl disable rsyslog
----
+
- Make `journald` store its log permanently (instead of at runtime only). In `/etc/systemd/journald.conf` set:
+
----
Storage=persistent
----

=== Setting Up command-not-found [[set-up-cnf]]

`command-not-found` is a helpful little program, which offers you to install the correct package when you type the command of a program that hasn't been installed yet. Fedora and Ubuntu do this automatically; in Debian, a little effort is needed.

. Install `command-not-found`:
+
[source,bash]
----
sudo apt install command-not-found
----
+
. Update the packages & commands database:
+
[source,bash]
----
sudo apt-file update
sudo update-command-not-found
----

=== Periodic Packages Cleaning

By default, the `apt` package manager keeps all downloaded packages on disk indefinitely. This can result in a lot of wasted disk space.

To configure `apt` to clean outdated downloaded packages periodically every 7 days (and keep only up-to-date packages), create the `/etc/apt/apt.conf.d/02periodic` file containing:

----
APT::Periodic::AutocleanInterval "7";
----

Or to periodically clean all downloaded packages regardless of them being up-to-date or not:

----
APT::Periodic::CleanInterval "7";
----

=== No Flat Audio Volumes [[no-flat-volumes]]

PulseAudio has developed two ways to synchronize audio volume between applications. Until recently, "flat volumes" have been the default. However, It is inherently problematic; see https://lists.fedoraproject.org/pipermail/devel/2015-September/214720.html[Disable PulseAudio flat volumes to prevent it from pushing volume level to max] and https://bugzilla.redhat.com/show_bug.cgi?id=1265267[Bug 1265267 - RFE: Disable PulseAudio's flat volumes].

Therefore, it has been decided to change the default setting to disabled flat volumes. Unfortunately, Debian (Stretch?) hasn't (yet?) integrated this update. To set it manually, open the `/etc/pulse/daemon.conf` file and add:

----
flat-volumes = no
----

=== Set Up Plymouth

Plymouth is the pretty animated picture you see when the system is booting up or shutting down. Debian doesn't like pretty stuff by default, and therefore, Plymouth has to be installed manually.

The process is https://wiki.debian.org/plymouth[documented on the Debian Wiki]. However, to save you a few clicks and some reading:

. Install Plymouth and its themes:
+
[source,bash]
----
sudo apt install plymouth plymouth-themes
----
+
. Edit the `/etc/initramfs-tools/modules` and add modesetting modules for your graphics card:
- For Intel GPUs:
+
----
# KMS
intel_agp
drm
i915 modeset=1
----
+
- For nVidia GPUs using the Nouveau driver:
+
----
# KMS
drm
nouveau modeset=1
----
+
- For AMD GPUs (may be slightly outdated):
+
----
# KMS
drm
radeon modeset=1
----
+
. Open the `/etc/default/grub` file.
. There, uncomment the `GRUB_GFXMODE=` line and set it to your display resolution. For example, `GRUB_GFXMODE=1024x768`. (This may not be necessary and might even uglify grub; test it.)
. Also, edit the kernel line, that is the one starting with `GRUB_CMDLINE_LINUX_DEFAULT=`. Add `splash` at the end and delete `quiet` if you'd like to be able to see detailed `systemd` boot output when you switch out of the pretty animated picture.
. Save the file and update `grub2`:
+
[source,bash]
----
sudo update-grub2
----
+
. Get the list of installed Plymouth themes:
+
[source,bash]
----
sudo plymouth-set-default-theme -l
----
+
The default theme in Debian Stretch is `softwaves`. The rest are either the themes of earlier Debian releases or are bundled with Plymouth itself, originally coming from Fedora.
+
. Set a theme for Plymouth to actually use:
+
[source,bash,subs=+quotes]
....
sudo plymouth-set-default-theme -R __your_selected_theme__
....
+
. Reboot and watch the result. Repeat the last two steps if you want to see more themes in action.

