= System Tuning [[system-tuning]]

== Common Options [[common-options]]

== XFS [[xfs]]

XFS is the default file system in Red Hat Enterprise Linux. It requires no tuning per se, but there are useful tools for it and things to consider when using XFS.

XFS is great for:

- large files
- large partitions
- parallel access to many files

Also, its kernel code is said to be very clean and maintainable, compared to ext4.

The CFQ disk scheduler, which is currently the default, enforces single-threaded access to the disk and, consequently, prevents XFS from utilizing its parallelism fully. To enjoy your parallelism, switch to a different scheduler: for example, deadline, or Kyber when using blk-mq. (For blk-mq, see <<blk-mq>>.) However, you should only do this on an SSD or another fast disk. HDDs perform best when access is single-threaded.

Some XFS-related tools:

- To get information about an XFS partition: `xfs_info`
- To back-up a file system: `xfsdump`
- To recover from back up: `xsfrestore`
- To repair an XFS file system: `xfs_repair`
- To calculate the fragmentation of a file system: `xfs_db -c frag -r <partition>`
- To defragment a file system: `xfs_fsr <partition>`

Red Hat documentation: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch-xfs.html[XFS in the Storage Administration Guide]

=== zswap [[zswap]]

`zswap` is a kernel feature, which compresses data in RAM that would otherwise need to be written to the swap partition. In effect, it increases the amount of data that can be stored in RAM, lowers swap partition usage, and increases overall system performance, especially when using a slow disk and little RAM.

It can be enabled using this kernel parameter in /etc/default/grub:

    zswap.enabled=1

After that, update `grub2` configuration as described in <<update-grub>> and reboot.

The current state of `zswap` can be read from the /sys/module/zswap/parameters/enabled file: 0 for off, 1 for on.

Run-time `zswap` statistics are recorded in the /sys/kernel/debug/zswap file.

=== journald [[journald]]

The current disk usage of `journalctl` can be displayed using the following command:

    sudo journalctl --disk-usage

`journald` configuration is located in the /etc/systemd/journald.conf file. It's probably a good idea to explicitly limit how much data `journald` can store. In the configuration file, set something like:

    SystemMaxUse=256M
    RuntimeMaxUse=128M

=== Block Device Multi Queue [[blk-mq]]

The multiqueue block layer can be enabled by setting the `scsi_mod.use_blk_mq=1` kernel parameter in /etc/default/grub.

The current value is available in the /sys/module/scsi_mod/parameters/use_blk_mq file.

The blk-mq has its own set of disk schedulers, which are multiqueue-capable. They can no longer be set using the `elevator` kernel parameter. They are configured by setting udev rules instead.

To configure blk-mq disk schedulers, create a /etc/udev/rules.d/60-scheduler.rules file containing something like this:

----
## Set the BFQ scheduler for all disks:
# ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="bfq"

## Set the BFQ scheduler for all rotational disks:
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1",           
  ATTR{queue/scheduler}="bfq"

## Set the Kyber scheduler for all non-rotational disks:
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0",           
  ATTR{queue/scheduler}="kyber"
----

If your kernel has been compiled with BFQ and Kyber set as modules, you also need to create the /etc/modules-load.d/schedulers.conf file. In it, put the module names to be loaded:

    bfq
    kyber-iosched

NOTE: The way the kernel detects rotational vs. non-rotational devices isn't very reliable. It falls back on rotational. All my flash drives have been detected as rotational for some reason. Therefore, configure the schedulers more explicitly if you want consistent behavior.

=== Memory Tuning for Interactive Use [[memory-tuning]]

https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[Certain people] argue that the way Linux handles interactive desktop usage leaves much to be desired. They also suggest ways to improve that.

In the /etc/sysctl.conf file, set:

    vm.swappiness=10
    vm.vfs_cache_pressure=50

Or, if you want to be more conservative, set:

    vm.swappiness=20
    vm.vfs_cache_pressure=80

In comparison, the default values are:

    vm.swappiness=60
    vm.vfs_cache_pressure=100

However, note that there is little "scientific" proof that modifying these actually helps. Experiment if you need to be sure. Rodd-O https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that[devises a way to test the impact] in their article mentioned earlier.

=== Update grub2 Configuration [[update-grub]]

After editing the /etc/default/grub file, the configuration has to be compiled for `grub2` to be able to use it:

- On Debian, all you have to do is type:
    sudo update-grub2
- On Fedora, follow these steps:
. Locate the compiled configuration file:

    sudo find /boot -name grub.cfg

. Copy the file name the previous command gave you and use it here:

    sudo grub2-mkconfig -o /path/to/grub.cfg

=== Setting Up the "Magic SysRq Keys" [[magic-sysrq]]

"Magic SysRq Keys" are keyboard shortcuts that are registered at the kernel level and allow you to control the basic functions of system even if it has otherwise completely frozen.

A common use case is to shut down the frozen system safely by typing `Alt`-`SysRq`-`s` to write (sync) all disk buffers, followed by `Alt`-`SysRq`-`u` to remount all disks read-only, and `Alt`-`SysRq`-`b` to reboot the system immediately.

Many more shortcuts are listed in the https://en.wikipedia.org/wiki/Magic_SysRq_key#Commands[Magic SysRq key] article on Wikipedia.

To set up Magic SysRq, open the `/etc/sysctl.conf` file as root and add:

    kernel.sysrq = 1

== Fedora-Specific Options [[fedora-specific]]

TODO

== Debian-Specific Options [[debian-specific]]

=== Configuring sudo [[sudo-config]]

// Add a reference to the Packages chapter
. Install the `sudo` package. This is already included in the _Packages_ chapter, but anyway, to make sure:

    su
    apt install sudo

. Add your user to the group `sudo`:

    usermod -a -G sudo your_user_name

=== journald as Default Log [[journald-default]]

By default, Debian uses `rsyslog` as the system log service. However, `journald` is running anyway all the time and there's no reason to have two log service, other than that `rsyslog` provides plain-text logs. If that doesn't sound compelling to you:

- Disable `rsyslog`:

    sudo systemctl disable rsyslog

- Make `journald` store its log permanently (instead of at runtime only). In `/etc/systemd/journald.conf` set:

    Storage=persistent

=== Setting Up command-not-found [[set-up-cnf]]

`command-not-found` is a helpful little program, which offers you to install the correct package when you type the command of a program that hasn't been installed yet. Fedora and Ubuntu do this automatically; in Debian, a little effort is needed.

. Install `command-not-found`:

    sudo apt install command-not-found

. Update the packages & commands database:

    sudo apt-file update
    sudo update-command-not-found

=== Periodic Packages Cleaning

By default, the `apt` package manager keeps all downloaded packages on disk indefinitely. This can result in a lot of wasted disk space.

To configure `apt` to clean outdated downloaded packages periodically every 7 days (and keep only up-to-date packages), create the `/etc/apt/apt.conf.d/02periodic` file containing:

    APT::Periodic::AutocleanInterval "7";

Or to periodically clean all downloaded packages regardless of them being up-to-date or not:

    APT::Periodic::CleanInterval "7";

